### ISSUE TITLE
Getting error "user is not a member of project" in api, even though the user is member of the project.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#122]
Description:

Getting error message  "userId: 41002174 the user is not a member of project 26912" even though the user is member of the project.

Steps to reproduce:

1. Create a Taas Project with TCConnCopilot account.
2.  Use TCConnCopilot account token and GET job with project Id.
3.  Observe the response

Expected result:
User should be able to view the response.

Actual result:
Getting "message": "userId: 41002174 the user is not a member of project 26912" with 401 Unauthorized status.

![image](https://user-images.githubusercontent.com/55895538/106568445-a42eaa00-6576-11eb-9b48-428de6e2eb97.png)
![image](https://user-images.githubusercontent.com/55895538/106568500-b872a700-6576-11eb-958f-c7f2267f1dde.png)

**Comment by sandhiyakavi** [comment]
Similar issue observed in https://github.com/topcoder-platform/taas-app/issues/25#issuecomment-769096860

**Comment by sandhiyakavi** [comment]
Verified.Working now.

![image](https://user-images.githubusercontent.com/55895538/108992734-fcbc1780-76dc-11eb-96b3-9f6f05b0af5e.png)

**Comment by lakshmiathreya** [comment]
@sandhiyakavi pls add Priority for this ...

**Comment by SathyaJayabal** [comment]
This was fixed by updating the m2m token scope.
