### ISSUE TITLE
Jobs not getting created when creating Project from Connect app

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#155]
Jobs not getting created when creating Project from Connect app. Caused by addition of duration when creating Jobs we are getting error from TaaS API 1.0, as duration field is only added in TaaS API 1.5

**Comment by sandhiyakavi** [comment]
@nkumar-topcoder @maxceem I verified the issue on Prod Env . But job is not getting created for me.

user role: Connect Copilot, Topcoder User, copilot

Projects created: https://platform.topcoder.com/taas/myteams/27237
https://platform.topcoder.com/taas/myteams/27235

![image](https://user-images.githubusercontent.com/55895538/108952021-47716b80-76ac-11eb-81b2-4589c5294ffd.png)

**Comment by sandhiyakavi** [comment]
Similar issue observed in previous release https://github.com/topcoder-platform/taas-apis/issues/122

**Comment by sandhiyakavi** [comment]
Verified.Working now.

![image](https://user-images.githubusercontent.com/55895538/108992882-25441180-76dd-11eb-99c1-cffe0fe5ebae.png)

**Comment by lakshmiathreya** [comment]
@sandhiyakavi this needs to be verified in Prod too right?
