### ISSUE TITLE
GET request not fetching the Work Period detail

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#180]
Description:

Getting 404 with "message": "id: 61d1a93a-6793-4b72-bcdc-c351cfca99e3 \"WorkPeriod\" not found" when tried to get the Work period by id
<img width="670" alt="post_bk_1" src="https://user-images.githubusercontent.com/55895538/113547598-314eb780-9629-11eb-9c03-2a5609c4bf0e.png">

<img width="676" alt="get_bk_2" src="https://user-images.githubusercontent.com/55895538/113547580-27c54f80-9629-11eb-8957-cfdb12337e89.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Able to get Work period detail using GET request

<img width="677" alt="bokingmanager_get" src="https://user-images.githubusercontent.com/55895538/113568136-eb0a5000-964a-11eb-990a-3e99832f1667.png">
<img width="675" alt="project_member_get" src="https://user-images.githubusercontent.com/55895538/113568148-ef366d80-964a-11eb-95d2-707e94dd3bdb.png">

**Comment by maxceem** [comment]
As this was only DEV issue and now is resolved, I'm closing it.
