### ISSUE TITLE
[$25] Able to set 'daysWorked' to any number of days for a WorkPeriod

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#181]
Description:

User is not able to set more than a week for startDate and EndDate but the 'daysWorked' can be set to any number of days (more than 7 days)

![image](https://user-images.githubusercontent.com/55895538/113568984-9d8ee280-964c-11eb-9082-345fa80f848d.png)

**Comment by maxceem** [comment]
The maximum number should be `5` as clarified by Will.

**Comment by maxceem** [comment]
Sum UP:
- we should not be able to set/update `daysWorked` to more than 5
- additionally, we should check that `daysWorked` respect start/end date of the corresponding Resource Bookings, so we could not set `daysWorked` more than can fit corresponding Resource Booking.

**Comment by maxceem** [comment]
@eisbilir one more issue if you like.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/c2eae5ff-2624-48da-a0c9-40f1316ca958

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/122721721-f7966000-d2ab-11eb-9aef-b1b789fc14fa.png)
![image](https://user-images.githubusercontent.com/55895538/122722004-36c4b100-d2ac-11eb-9a4b-d6a07a5ec72c.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder . daysWorked cannot be set more than it can fit the RB dates
