### ISSUE TITLE
RB adds extra date because of different timezone.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#196]
Description:
RB adds extra date because of different timezone which in turn adds extra WP's.

Steps to Reproduce:
1. Create RB with only enddate. (14/4/2021)
2.  Edit RB date by adding start date (10/4/2021) from UI.
3.  GET RB details using endpoint (api) and observe. (start date is (9/4/2021))
4. Observe the WP created for the RB (one WP created in extra).

since in UI it uses timezone of our browser, in api it uses UTC timezone and WorkPeriods it calculates using EDT timezone.

<img width="960" alt="doubt" src="https://user-images.githubusercontent.com/55895538/115200143-db9d0380-a12e-11eb-8fc5-9bdcf8a4ee3e.png">
<img width="646" alt="doubt_2" src="https://user-images.githubusercontent.com/55895538/115200160-de97f400-a12e-11eb-8a61-93c97251d45e.png">
![image](https://user-images.githubusercontent.com/55895538/115200246-f4a5b480-a12e-11eb-83a8-afdd6f7e28e1.png)

**Comment by maxceem** [comment]
We removed timezones and time from the Resource Bookings https://github.com/topcoder-platform/taas-apis/issues/204, so this should be no longer an issue.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Displaying correctly now.

<img width="630" alt="new_change" src="https://user-images.githubusercontent.com/55895538/115706688-df3bbf00-a3a8-11eb-8347-aabe0f575186.png">
<img width="676" alt="new_change_2" src="https://user-images.githubusercontent.com/55895538/115706696-e236af80-a3a8-11eb-84c4-1ed7f904ce97.png">

**Comment by maxceem** [comment]
Closing as it was a DEV issue only.
