### ISSUE TITLE
[$40] Should not be able to remove RB's start/end date once created

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#202]
Once Resource Booking has both start and end dates, we create WorkPeriods for it.

We should not allow removing start/end dates if both of them already set for Resource Booking.

- Throw an error if the user tries to do so.
- Create unit tests to cover all the cases:
   - should not allow setting dates to null if both dates are not null
   - should allow setting dates to null if one of the dates is null
   - should allow setting dates to null if both dates are null
- Make sure that Postman is up to date and doesn't have broken endpoints after this.
   
Related TaaS App issue https://github.com/topcoder-platform/taas-app/issues/146

**Comment by maxceem** [comment]
@eisbilir one more issue if you like.

**Comment by eisbilir** [comment]
@maxceem sure

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/a370aaab-4341-4f23-a7be-490a171f598e

**Comment by sandhiyakavi** [comment]
Verified below scenarios in dev Env.
1. Error message if user tried to remove Start/End date/both once set.
![image](https://user-images.githubusercontent.com/55895538/122708411-176f5900-d297-11eb-8cf9-18a3007a010e.png)
![image](https://user-images.githubusercontent.com/55895538/122708452-2fdf7380-d297-11eb-98e7-605566debe63.png)

2. Able to remove start/End date if one is already null.

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
