### ISSUE TITLE
Able to update payment amount for Workperiodpayments even when challenge is completed

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#208]
Description:

Able to update payment amount for Workperiodpayments even when challenge is completed. 

<img width="677" alt="update_prizeamount_challenge" src="https://user-images.githubusercontent.com/55895538/115522369-01f5a700-a2c7-11eb-86fc-1dc5d3e9fb2d.png">

The amount is not changed in Challenge as it is in 'Completed' status

<img width="957" alt="update_prizeamount_WM" src="https://user-images.githubusercontent.com/55895538/115522380-04580100-a2c7-11eb-83ba-5cfb2a158a5a.png">

**Comment by SathyaJayabal** [comment]
@maxceem , once payment status is complete, there should not be any updates to the record.

**Comment by maxceem** [comment]
We no longer can update `amount` as per https://github.com/topcoder-platform/taas-apis/issues/288.

**Comment by sandhiyakavi** [comment]
Verified on dev Env. We are no longer able to update amount

![image](https://user-images.githubusercontent.com/55895538/122861656-c163e980-d35a-11eb-8140-f590789d78ed.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder .
