### ISSUE TITLE
Ability to get Resource Bookings together with Work Periods

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#212]
We are going to implement the next UI for admins to list ResrouceBookings (RB) together with the WorkPeriod (WP):

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/146016/117113683-80f0e200-ad93-11eb-87fe-b1e80c45a6cb.png">

We have to be able to get data that is necessary for this page with abilities to filter, sort and paginate (ignoring Alerts).

**Comment by maxceem** [comment]
## Context

### Project Context

Topcoder TaaS API - is the main backend service for the [Topcoder TaaS App](https://platform.topcoder-dev.com/taas/myteams) which helps us to manage talent requests from the clients.

### Challenge Context

In the TaaS API we have **Resource Bookings** (RB) that represent a member assigned to some work for some time period from "startDate" till "endDate". We already have a model and endpoints implemented for them. We want to be able to process payments for Resource Bookings by weeks. For this purpose we already created a model WorkPeriod that represents weeks and corresponding endpoints for **Work Periods** (WP) in the [previous challenge](https://www.topcoder.com/challenges/3779f061-9471-4b87-9b7e-d91589b77aa6?tab=details). There is a new [design for TaaS Admin App](https://monosnap.com/file/HryMhB6QWesqrcH2XbXWhGjXa2UHP5) which we have to support that requires us to be able to get **Resource Bookings** together with **Work Periods** in one endpoint with filter and sorting abilities.

## Expected Outcome

Endpoint which would retrieve, filter, sort and paginate all the data required for [this](https://monosnap.com/file/HryMhB6QWesqrcH2XbXWhGjXa2UHP5) admin page.

## Challenge Details

### Technology Stack

- Node.js
- PostgreSQL
- ElasticSearch

### Code access

The work in this challenge would be done in 2 repositories:
- https://github.com/topcoder-platform/taas-apis branch **feature/work-periods-automation**
- https://github.com/topcoder-platform/taas-es-processor branch **feature/work-periods-automation**

Environment variables necessary to run this service would be shared on the forum. Or you would see them after registering to this challenge below under "Registered User Additional Information".

### Individual requirements

#### Automation and Constraints

- Remove support for statuses 'sourcing', 'in-review' for Resource Bookings in both **TaaS API** and **TaaS ES Processor**. Default status should be 'assigned'.
- When ResourceBooking is created we should create Work Periods as per the logic which is described in the section [ResourceBooking is created](https://github.com/topcoder-platform/taas-apis/wiki/TaaS---Scope,-Status-and-permissions#resourcebooking-is-created). 
- When we change 'startDate' or 'endDate' for ResourceBooking we have to update corresponding Work Periods as per logic in section [ResourceBooking startDate or endDate is changed](https://github.com/topcoder-platform/taas-apis/wiki/TaaS---Scope,-Status-and-permissions#resourcebooking-startdate-or-enddate-is-changed). 
- If we are deleting Resource Booking all associated Work Periods should be deleted in DB and ES. With the next constraints:
   - We should not allow deleting Work Period if its paymentStatus is 'partially-completed' or 'completed'. Update endpoint "DELETE /v5/workPeriods/:id" to return error if we trying to do so.
   - We should not be able to change status of ResourceBooking to 'cancelled' or delete ResourceBooking if there is at least one associated Work Period with paymentStatus 'partially-completed' or 'completed'. Return error if we try to do so by any endpoint.
- Create a migration script inside "migrations" folder which would create WorkPeriods for the existent ResourceBookings. When runinnig migration we should be able to config environment variables "MAX_START_DATE" and "MAX_END_DATE" so we would only process Resource Bookings when "startDate &lt; MAX_START_DATE and endDate &lt; MAX_END_DATE".

#### Tests

Currently, almost all of the tests are outdated and borken. We would start creating good tests starting this challenge. 
- Please, remove all existent tests except of 'autoWrapExpress test' which seems to work. 
- Create tests which would check all the requirements in this challenge.
- We don't require any code coverage percentage, but we want to have tests which would really check the logic requirements which we have.
- For example for create/update Work Periods we would like to test all the possible edge cases: 
   - success cases which cause 'dayWorked' changing: startDate is extended inside one week, startData is reduced inside one week, endDate is extended inside one week, endDate is reduced inside one week
   - success cases which cause WorkPeriods removeing/adding: startDate is extended to another week, startData is reduced to another week, endDate is extended to another week, endDate is reduced to another week
   - success cases with paid weeks: startData is reduced from not paid week to paid week, endDate is reduced from not paid week to paid week
   - fail cases with paid weeks: startData is reduced from paid week to another week, endDate is reduced from paid week to another week
 - The cases above is just for reference to give an idea. In general we would like to tests all the cases which are essential for the logic.

### General requirements

- WorkPeriods represent weeks from Sunday to Saturday. But at any given time we can know what is the day only when we know timezone. Create a config/env variable which would define in what timezone all the WokePeriods would be calculated. For now config [EDT](https://www.timeanddate.com/time/zones/edt) timezone. So when creating WorkPeriods correctly calculate the dates from start/end dates of ResourceBookings. Note, that ResourceBookings start/end dates might be stored in any timezone.
- To implement logic for creating/updating WorkPeriods we already have a good place to handle create/update events for ResourceBooking in [ResourceBookingEventHandler.js](https://github.com/topcoder-platform/taas-apis/blob/e68f038e60fb41e2c5065de2428e8d58b0a38ea6/src/eventHandlers/ResourceBookingEventHandler.js). Put logic into separate functions.
- Update Swagger and Postman if needed.
- Follow the code structure and practices that are established in our code.
- Split code into reusable methods where applicable.
- "npm run test" should work good after this challenge.
- Lint should pass.

## Scorecard Aid

- Please, follow the scorecard rules to evaluate this challenge. 
- Code quality is important to us too and it has to be evaluated in the corresponding sections of the scorecard.
- Tests should properly cover requirements in this challenge.
- If there is some test which claims to test something but in reality it doesn't test it - this is very bad, and such cases should be additionally penalized as minor issues.

## What To Submit

- Submit a zip file which would include:
  - a [Git patch](https://stackoverflow.com/questions/5159185/create-a-git-patch-from-the-uncommitted-changes-in-the-current-working-directory) with changes you’ve made to the code in our repository
  - don't need to mention commit hash
- Additionally, the winner would be required to raise a pull request to the repository after the challenge is completed.

**Comment by maxceem** [comment]
#### Permissions

- Endpoints **"GET /resourceBookings"** and **"GET /resourceBookings/:id"** should only return "memberRate", "workPeriods.memberRate" and "workPeriods.payments" fields to the user who is "Booking Manager", "administrator" or M2M token with correct scope (see for example how it's done for "interviews" inside Job Candidates).
- Fix endpoints **"GET /work-periods"** and **"GET /work-periods/:id"** to only return "memberRate" and "payments" fields to the user who is "Booking Manager", "administrator" or M2M token with correct scope (at the moment they don't check scope).

**Comment by sandhiyakavi** [comment]
Specifications mentioned in https://github.com/topcoder-platform/taas-apis/issues/212#issuecomment-833353039 are not yet fully implemented. cc: @maxceem 

Other than that, tested the below scenarios. Working as expected

1. Verify "GET /resourceBookings" enpoints to return ResourceBookings together with WorkPeriods by specifying fields query param.
2.  Verify  filtering by "projectId", "workPeriods.endDate", "workPeriods.startDate", "workPeriods.paymentSatus" is possible both by single filter and multiple filter combinations.
3.  Verify sorting by "startDate", "endDate", "workPeriods.memberHandle", "workPeriods.customerRate", "workPeriods.paymentStatus", "workPeriods.daysWorked" is possible.
4. Verify whether filtering and sorting by other fields in RB and WP is also possible (id, rateType, startDate, endDate, customerRate, memberRate, status, workPeriods.userHandle, workPeriods.daysWorked, workPeriods.customerRate, workPeriods.memberRate, workPeriods.paymentStatus)
5. Verify whether filtering by invalid attributes returns error.
6. Verify error returned if the field param has sorting by workperiods.* and no WP start /end date

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder .
