### ISSUE TITLE
Don't allow canceling Resource Bookings if some payment was done or in progress

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#216]
It should follow the same constraints as during Resource Booking removing here https://github.com/topcoder-platform/taas-apis/issues/203

**Comment by maxceem** [comment]
we already implemented it here: https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/ResourceBookingService.js#L78

probably we have to update the code, so this constraint is placed in some logical place, or update the name of the helper method, as now it's unexpected to find this check there.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

1. Getting below error message if WP payment status is 'scheduled', 'in-progress' or 'completed'
![image](https://user-images.githubusercontent.com/55895538/122877166-435f0d00-d371-11eb-87c3-4b80f901d940.png)

2. Able to cancel RB for other WP payment status

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder .
