### ISSUE TITLE
The daysworked is not null in exisitng older WP records.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#221]
Description:
The daysworked is not null in exisitng older WP records.

![image](https://user-images.githubusercontent.com/55895538/115855669-7adf3500-a466-11eb-9b3c-311b6ae295d6.png)

**Comment by sandhiyakavi** [comment]
@maxceem The daysworked are correctly displaying as null after re-creation.

![image](https://user-images.githubusercontent.com/55895538/115859151-c0056600-a46a-11eb-9381-5768a04dc654.png)

**Comment by maxceem** [comment]
Closing, as it was a DEV issue only.
