### ISSUE TITLE
Work Period Updates

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#223]
feat: WorkPeriods model and CRUD endpoints via PRs: #178 and topcoder-platform/taas-es-processor#31 by challenge https://www.topcoder.com/challenges/3779f061-9471-4b87-9b7e-d91589b77aa6?tab=details
feat: WorkPeriods automation and constraints via PRs: #190 and topcoder-platform/taas-es-processor#37 by challenge https://www.topcoder.com/challenges/00080061-9cca-49fd-90d6-0ca64dc776fd
feat: actual payment processing via PR #183 by the challenge https://www.topcoder.com/challenges/52fd3784-4bff-42f9-8ba8-a8a65db05803
feat: WorkPeriodPayments model and CRU endpoints + integration with payment processing via PRs: #198 and topcoder-platform/taas-es-processor#42 by challenge https://www.topcoder.com/challenges/7424ea7e-8c4e-495f-bcdd-e80dce0efbc2 + task https://www.topcoder.com/challenges/bf9b65a6-4f4b-4edc-a277-5be9913e659c
feat: Create script for migrating "isApplicationPageActive" from CSV file #173
feat: Create proxy endpoint GET /taas-teams/me #154 + #170
local development process improvement: "npm run init-db" should init already done migrations #147

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. All Work Period updates are working as expected.
