### ISSUE TITLE
deletedAt field missing in new Interview model

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#240]
Description:
'deletedAt' field missing in Interview model.

![image](https://user-images.githubusercontent.com/55895538/117778759-f0c20980-b278-11eb-8dcf-5e9c63366ae5.png)

**Comment by urwithat** [comment]
This was missing in TaaS ES Processor, and existing in TaaS API.
Has now been added back to TaaS API Interviews.
@sandhiyakavi / @SathyaJayabal - Kindly test

**Comment by sandhiyakavi** [comment]
@urwithat Still not able to get deleteAt field

![image](https://user-images.githubusercontent.com/55895538/118073962-fa1db400-b3e7-11eb-9f13-9889902f5c17.png)

**Comment by SathyaJayabal** [comment]
@urwithat , dont see the deleted_at field yet. the interview is cancelled.
<img width="1440" alt="Screenshot 2021-05-13 at 12 03 24 PM" src="https://user-images.githubusercontent.com/58783823/118087537-55997300-b3e3-11eb-9078-9bb591e793da.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. 

![image](https://user-images.githubusercontent.com/55895538/118446309-7555d180-b72a-11eb-9870-bcb586bec38e.png)
