### ISSUE TITLE
Add interview round in email template

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#251]
https://github.com/topcoder-platform/taas-app/issues/260

**Comment by sandhiyakavi** [comment]
Verified on Dev.

![image](https://user-images.githubusercontent.com/55895538/118470891-17cd7f00-b742-11eb-9cc7-fb4542979b78.png)

**Comment by SathyaJayabal** [comment]
verified in prod
https://github.com/topcoder-platform/taas-app/issues/260
