### ISSUE TITLE
Make the BA a string while creating a challenge for WP payment

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#255]
Make the BA a string while creating a challenge for WP payment
https://topcoder.slack.com/archives/C01T50SRHDE/p1621338405002000
cc @nkumar-topcoder

**Comment by nkumar-topcoder** [comment]
@sandhiyakavi @SathyaJayabal This is fixed in DEV. please check.

cc @maxceem

**Comment by sandhiyakavi** [comment]
@nkumar-topcoder @maxceem  Currently I am getting "Billing account is not assigned to the resource booking" error with 409 conflict status eventhough billing account is assigned to the Resource Booking . Hence not able to create Work period payments for the same.

Sample: https://platform.topcoder-dev.com/taas/myteams/17340/rb/81dbce93-1167-4bff-8125-de8ad0d34778
BillingAccountId added to RB: 80000068
WP : 1669110d-be05-4ca6-8e38-9a9b64081942

![image](https://user-images.githubusercontent.com/55895538/118804649-eb4f6980-b8df-11eb-96b8-fbac7404f07f.png)
![image](https://user-images.githubusercontent.com/55895538/118804731-07530b00-b8e0-11eb-9d7a-9528657d87d2.png)

**Comment by sandhiyakavi** [comment]
Verified on Dev. 

<img width="631" alt="WP-paymentBA" src="https://user-images.githubusercontent.com/55895538/119083056-3b424380-ba3a-11eb-9da1-97a54eafc498.png">
<img width="628" alt="challenge_bA" src="https://user-images.githubusercontent.com/55895538/119083063-3ed5ca80-ba3a-11eb-9318-ed905e872104.png">
![Uploading image.png…]()

**Comment by SathyaJayabal** [comment]
verified on prod. 
<img width="1011" alt="Screenshot 2021-05-27 at 1 47 16 PM" src="https://user-images.githubusercontent.com/58783823/119791033-121a2b00-bef2-11eb-9d7f-b0baeb926e0b.png">
