### ISSUE TITLE
GET resourceBookings does not return member rate 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#26]
GET resourceBookings does not return member rate 
<img width="584" alt="Screenshot 2020-12-02 at 4 17 54 PM" src="https://user-images.githubusercontent.com/58783823/100863031-f6d9e000-34b9-11eb-8e07-c617505e2a52.png">

This is the resource booking that was created with member rate
<img width="710" alt="Screenshot 2020-12-02 at 4 18 33 PM" src="https://user-images.githubusercontent.com/58783823/100863112-140eae80-34ba-11eb-8578-86fe65e2a3cb.png">

**Comment by nkumar-topcoder** [comment]
@SathyaJayabal this as per design. We only display customer rate.
this can be closed
