### ISSUE TITLE
BA Id of Resource Booking changed to null each time RB dates are edited.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#260]
Description:

BillingAccount Id of Resource Booking changed to null each time RB dates are edited.

Steps to Reproduce:
1. PATCH RB by adding BillingAccount Id.
2.  Edit the Start date/End date of the RB.
3.  Check the BillingAccount Id of the RB.

Actual Result:
BillingAccountId changed to 'null' each time the start date/End date edited.

<img width="665" alt="issue_with_update" src="https://user-images.githubusercontent.com/55895538/119085766-4ea3dd80-ba3f-11eb-89bf-0e711db5288e.png">
<img width="631" alt="after_editing" src="https://user-images.githubusercontent.com/55895538/119085770-519ece00-ba3f-11eb-8429-dedb0c044fa7.png">

**Comment by maxceem** [comment]
@sandhiyakavi I guess you used `PUT` request instead of `PATCH`. `PUT` one overrides all the fields. If so, do you think we can close this issue?

**Comment by sandhiyakavi** [comment]
@maxceem I updated the RB start and End date from UI

**Comment by maxceem** [comment]
ah, got it, so this is issue in TaaS App

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. BA is not changed to null even after updating RB dates in UI

<img width="626" alt="BA_still present" src="https://user-images.githubusercontent.com/55895538/119932287-ee241b80-bfbd-11eb-9734-c55d1f564f67.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
