### ISSUE TITLE
Check if member of project when getting WorkPeriod

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#269]
When we try to get a WorkPeriod by id by the user who doesn't have privileges, such requests always fallback to DB due to internal error, see log:

[2021-05-27T08:02:46.580Z] WorkPeriodService getWorkPeriod ERROR : cannot GET /v5/projects/undefined (404)
[2021-05-27T08:02:46.580Z] WorkPeriodService getWorkPeriod INFO : try to query db for data
[2021-05-27T08:02:47.131Z] helper checkIsMemberOfProject DEBUG : the members of project 111: [22880988,40152933,40152856], authUserId: 40152856

**Comment by maxceem** [comment]
Fixed by @eisbilir via https://github.com/topcoder-platform/taas-apis/pull/261

Payment for the tasks processed https://www.topcoder.com/challenges/c33884ce-da9b-4a1e-bfcd-d15b2b931ed5

**Comment by maxceem** [comment]
QA guidelines:
- Check that normal user (non-manager and non-admin) can access work periods inside the project they are part of. And cannot access work periods in the projects where they are not part of

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/121633969-c2755b00-cabe-11eb-9cc9-8dcd63a269c9.png)
![image](https://user-images.githubusercontent.com/55895538/121634020-d5882b00-cabe-11eb-90cf-0f9de5eeb1b6.png)
![image](https://user-images.githubusercontent.com/55895538/121634596-cce42480-cabf-11eb-96fb-6203e534b45b.png)

If not a member of the project
![image](https://user-images.githubusercontent.com/55895538/121634701-03ba3a80-cac0-11eb-8acf-03f958d7a6e7.png)
![image](https://user-images.githubusercontent.com/55895538/121635331-05383280-cac1-11eb-99c5-e1c8e94adda4.png)

![image](https://user-images.githubusercontent.com/55895538/121634752-1896ce00-cac0-11eb-9783-9a9c934aaf8c.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

Able to view WP if member of project
![image](https://user-images.githubusercontent.com/55895538/122374393-4f2b8780-cf9d-11eb-90ab-87ab6fed9dc6.png)
![image](https://user-images.githubusercontent.com/55895538/122374462-5c487680-cf9d-11eb-8d58-07967b060245.png)

Not able to view WP if not member of the project.
![image](https://user-images.githubusercontent.com/55895538/122374638-813ce980-cf9d-11eb-8057-357315c4f4ff.png)
![image](https://user-images.githubusercontent.com/55895538/122374720-944fb980-cf9d-11eb-9d37-1ab4e148c49c.png)
