### ISSUE TITLE
Use v5/members instead of v3/members

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#270]
At the moment we are using "v3/members" endpoint to get users by the handle in 2 places, we have to update them to use "v5/members" instead.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/taas-apis/pull/271

**Comment by maxceem** [comment]
QA guidelines:
This update would affect 2 features that we would have to verify:
- Create a WorkPeriodPayment. A challenge should be created with a winner listed correctly.
- Add 2 or more members to the team with one request. They should be added successfully.
- Add some non-existent members to the team - we should get a correct error that user(s) don't exist.

**Comment by sandhiyakavi** [comment]
@maxceem Tried Creating WorkPeriod Payment but both are still in Active status and not moved to "completed" status yet.Hence not able to check Winner listed.

WP Payment Ids: 4221b74a-38c3-43b2-99ca-e16e1e3ad359, 45e43570-435e-4db1-a351-a859d4ebd897
Challenge : https://www.topcoder-dev.com/challenges/ba6a5bbf-9907-404b-af69-a1ed8abf9e04
https://www.topcoder-dev.com/challenges/5701c582-3152-46e1-a0f2-04296b2cbd0f?tab=details

![image](https://user-images.githubusercontent.com/55895538/119819874-d2703500-bf2b-11eb-94ca-7e7cd65529d0.png)

2. Added more members with handle/email id. Getting added successfully.
3.  Getting correct user(s) don't exist error for invalid members
<img width="957" alt="user_doesn't exist" src="https://user-images.githubusercontent.com/55895538/119820139-1f540b80-bf2c-11eb-8723-078cf91dbed4.png">
<img width="960" alt="user_doesn't eist" src="https://user-images.githubusercontent.com/55895538/119820172-2713b000-bf2c-11eb-85cb-2cd13fb94736.png">

**Comment by sandhiyakavi** [comment]
@maxceem @nkumar-topcoder The challenge not moved to "completed" status was because of BA. It's moving to completed status now.

![image](https://user-images.githubusercontent.com/55895538/119825983-85dc2800-bf32-11eb-97e6-9cb1c0b4cde2.png)
 
Winner detail is also updated in challenge api, 
![image](https://user-images.githubusercontent.com/55895538/119826135-ac01c800-bf32-11eb-97bc-5d36bd8ec9cf.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder .
