### ISSUE TITLE
500 Internal server error on Taas JOBs api

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#282]
Unable to create job either from Connect while creating a team or from taas FE

<img width="1440" alt="Screenshot 2021-06-01 at 9 52 35 AM" src="https://user-images.githubusercontent.com/58783823/120266394-6c830500-c2bf-11eb-9c41-0ce275ae6068.png">

**Comment by SathyaJayabal** [comment]
verified, fixed on dev, able to create jobs
<img width="1440" alt="Screenshot 2021-06-01 at 10 34 23 AM" src="https://user-images.githubusercontent.com/58783823/120269245-0f8a4d80-c2c5-11eb-8574-c481c4dc513d.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

Able to create Job from Connect/Taas app
