### ISSUE TITLE
[Role API] Returns invalid skills message when creating a role with valid skills

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#292]
**Steps**
Call create role end point with the below skills set(these skills appear in the skills page in the intake app)
"listOfSkills": [
        "JavaScript",
        "Java",
        "CSS",
        "Git",
        "React.js",
        "Angularjs",
        ".Net",
        "Actian Database",
        "C++",
        "C",
        "Commerce Server 2009",
        "IBM Rational Application Developer",
        "IBM Websphere Application Server",
        "R",
        "Vert.X",
        "yii"
    ],

**Current behavior**
Returns {    "message": "skills: \"javascript,java,css,git,angularjs,.net,vert.x\" are not valid"}

**Expected behavior**
Should create the role since these are valid skills

Note: But if you send the same request by removing some skills like    "IBM Rational Application Developer" and  "IBM Websphere Application Server", from the above skills list, it creates the role

This is common to update end point too

**Comment by eisbilir** [comment]
@nikolay83 
PR created: #299

**Comment by sdgun** [comment]
Verified with multiple sets of skills and roles were created without an issue with the given skills.
