### ISSUE TITLE
[Role API] The skills and keyword search does not return any results

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#293]
**Steps**
Call GET https://api.topcoder-dev.com/v5/taas-roles/?skillsList=aws lambda&keyword=aws from a valid user token

**Current behavior**
Search by both skills and keyword does not return results

**Expected behavior**
Should return matching results

**Comment by eisbilir** [comment]
@sdgun @nikolay83 
To make it clear, we expect matching results to have both `aws lambda` skill in it's skillsLists and include `aws` in it's name, right?
Both condition should be satisfied. It might be deleted after but I couldn't find any matching roles at GET https://api.topcoder-dev.com/v5/taas-roles/

I made both skillList and keyword criteria case **insensitive** now.
PR created: #299

**Comment by sdgun** [comment]
@eisbilir Noticed keyword is still case sensitive.

https://user-images.githubusercontent.com/4592712/120761144-7fe9d680-c532-11eb-87d7-efe7bc6e1304.mp4

@nikolay83 Are we only checking keyword in the name?

> @sdgun @nikolay83
> To make it clear, we expect matching results to have both `aws lambda` skill in it's skillsLists and include `aws` in it's name, right?
> Both condition should be satisfied. It might be deleted after but I couldn't find any matching roles at GET https://api.topcoder-dev.com/v5/taas-roles/
> 
> I made both skillList and keyword criteria case **insensitive** now.
> PR created: #299

**Comment by eisbilir** [comment]
@nikolay83 Could you confirm Role index is recreated with new mapping settings after this fix?
Because searching works good on local

**Comment by nikolay83** [comment]
Confirmed.

**Comment by sdgun** [comment]
Cannot verify until https://github.com/topcoder-platform/taas-app/issues/342 is fixed.

**Comment by sdgun** [comment]
This issue still exists in Dev. Both skills list and keyword are case sensitive

https://user-images.githubusercontent.com/4592712/123069364-597fd280-d430-11eb-8d51-91a41c59b78c.mp4

**Comment by sdgun** [comment]
@nikolay83 Please note this issue is not fixed yet


https://user-images.githubusercontent.com/4592712/123196191-1c1a5400-d4c7-11eb-993c-61796882534f.mp4

**Comment by eisbilir** [comment]
@nikolay83 @sdgun 
This was failing because no re-indexing was done after fix.
According to https://github.com/topcoder-platform/taas-apis/issues/370#issuecomment-869324337 , re-indexing is now done.
So both skills list and keyword should be case insensitive now.

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed now.
