### ISSUE TITLE
Populate "resourceBooking" response with "job.description"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#30]
When we are showing the list of "resourceBooking" in UI, we are also showing the "job.description" and need "job.skills" to calculate the percentage of matching skills:

![image](https://user-images.githubusercontent.com/146016/100909925-f8b19c80-34d5-11eb-874a-77c6f1e237f7.png)

As resources might belong to different jobs, getting multiple jobs client-side might cause too many requests. Instead, can we populate "resourceBooking" objects with "job.description" and "job.skills" field values?

There are 2 ways to go:
1. Just add 2 fields to the response `jobDesctipion = job.description` and `jobSkills = job.skills`.
2. Or more general way. Add a query param `fields` which would define the list fields to return.
    - by default only all "resourceBooking" fields would be returned
    - if we define `fields` query param then return only listed fields
    - we can define "resourceBooking" fields like `fields=id,jobId,status` and we also can define fields of the corresponding job like this: `fields=id,jobId,status,job.description,job.skills,job.description` which should return a "resourceBooking" booking object with populated fields:
    ```js
    {
       id: "id",
       jobId: "jobId",
       status:  "...",
       job: {
         description: "Developer",
         skills: [...]
       }
    }
    ```

@nkumar-topcoder what do you think?

**Comment by maxceem** [comment]
Regarding matching. I can see that API returns the` skillMatched` value. Though in UI when we hover `more` link we are also showing which skill are matched and which are not, like this:

![image](https://user-images.githubusercontent.com/146016/100984753-ca72a200-3553-11eb-9502-8a1171ec944c.png)

To show this, we need to know the list of the skills which are required by the job. And the list of skills which candidate for this job has.

**Comment by nkumar-topcoder** [comment]
@maxceem 
if this simple fix let's add as task. else we can take this as new scope in next version

cc: @wdprice

**Comment by maxceem** [comment]
@nkumar-topcoder after discussing with you on the call, we came up to the idea, that we have almost everything we need already. We only have to add `jobId` to the resources. 

So I've created a new issue for this https://github.com/topcoder-platform/taas-apis/issues/36.

And I'm closing this one.
