### ISSUE TITLE
WP payment amount set to memberRate instead of 0 if workperiods.daysWorked is zero

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#305]
Description:
WP payment amount is getting set to RB.memberRate instead of 0 if workperiods.daysWorked is set to 0.

Steps to Reproduce:
1. Set the workperiod.daysworked=0
2.  Set RB.memberRate to some value. (WP.memberrate is null)
3.  Post/Work-period-payments with body containing only WP id.

Expected Result:
If WP.daysworked set as '0' then amount is also set as zero.

Actual Result:
Amount is set to RB.memberRate.

<img width="548" alt="days_worked_set_to_0" src="https://user-images.githubusercontent.com/55895538/120637933-7583fa00-c4aa-11eb-8627-935d511f69a1.png">
<img width="536" alt="ampunt_daysworked_0_wrong" src="https://user-images.githubusercontent.com/55895538/120638093-abc17980-c4aa-11eb-8815-2218f7569688.png">

@maxceem @nkumar-topcoder But WP payments Amount field allows only floating numbers more than 0.
![image](https://user-images.githubusercontent.com/55895538/120638535-30ac9300-c4ab-11eb-94f4-87d144ab9a30.png)

**Comment by nkumar-topcoder** [comment]
@sandhiyakavi  yes, verified valid issue

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Error msg is displayed now.

![image](https://user-images.githubusercontent.com/55895538/122721199-57d8d200-d2ab-11eb-9b19-cf7b15c0a937.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder .
