### ISSUE TITLE
[$20] WP payment in batch: Getting response like payment Id created with memberRate missing error.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#307]
Description:
While trying WP payment in batch, if there is a record with missing member rate, then the response for that record is like WP payment Id and status as "scheduled" created along with the error message.

Note: But if we try to GET by the Id, displays like "Workperiod Payment" not found"
sample WP payment Id: 58fe397a-42be-4d57-bbf6-5a6bb3edcb73

Sample batch request: [{
   [{"workPeriodId": "9a259454-2f56-43aa-b7c3-00a2d0733675"},{"workPeriodId": "1585cf31-cfb9-4770-89d0-978569337828"},{"workPeriodId": "cd3ce6df-e65b-48eb-bcdd-7a2df5c4d11c"},{"workPeriodId": "6325c84e-e7fd-4da5-880e-2744a79c033e"},
{ "workPeriodId": "4a36983e-1c37-45eb-9f14-6ca551345b63"}]

Response:
![image](https://user-images.githubusercontent.com/55895538/120753586-5a66c800-c546-11eb-8867-7227140b5c74.png)

![image](https://user-images.githubusercontent.com/55895538/120753793-a4e84480-c546-11eb-8724-5286b5da5a9a.png)

Also, for BA missing error Only error message is shown

![image](https://user-images.githubusercontent.com/55895538/120754156-3bb50100-c547-11eb-8c79-67d0fde22dcd.png)

**Comment by maxceem** [comment]
This is a valid issue, we have to update the logic, so in case of error it only returns the `workPeriodId` and `error` no other fields.

**Comment by maxceem** [comment]
@xxcxy would you like to work on this?

**Comment by maxceem** [comment]
The same issue when we are creating a single payment https://github.com/topcoder-platform/taas-apis/issues/323.

**Comment by maxceem** [comment]
Sum up:
- If some error happens during scheduling payment and the actual payment is not created we should only return `workPeriodId` and `error` no other fields.

**Comment by maxceem** [comment]
This one is fixed and ready for QA. It appears that it's different from #323.

**Comment by sandhiyakavi** [comment]
Verified on Dev. No WP payment Id is created now.

![image](https://user-images.githubusercontent.com/55895538/121492086-87691e00-ca11-11eb-8340-d28483d703c3.png)

sample 
```
[{
    "workPeriodId": "cc42e4b0-7134-47e1-af30-21d35acab280"},{"workPeriodId": "ec007094-bb57-4bc0-bd11-00bf8fb7fa07"},{"workPeriodId": "b757c178-7f7f-45b9-88f3-10ce469ed78b"},{ "workPeriodId": "22d49927-d9b7-4115-8b82-aea72d44ee73"
},{"workPeriodId": "5e8c3e52-539d-45d0-8e66-37be3709b5f4", "amount":3456.22},{ "workPeriodId": "b7132e7c-7947-458c-829f-59bcda44da91"}]
```
response:
```
[
    {
        "workPeriodId": "cc42e4b0-7134-47e1-af30-21d35acab280",
        "error": {
            "message": "id: e09cc7d8-d898-41b2-a73d-13e569b98948 \"ResourceBooking\" Billing account is not assigned to the resource booking",
            "code": 409
        }
    },
    {
        "workPeriodId": "ec007094-bb57-4bc0-bd11-00bf8fb7fa07",
        "error": {
            "message": "Can't find a member rate in work period: ec007094-bb57-4bc0-bd11-00bf8fb7fa07 to calculate the amount",
            "code": 400
        }
    },
    {
        "workPeriodId": "b757c178-7f7f-45b9-88f3-10ce469ed78b",
        "billingAccountId": 80000068,
        "id": "f9782cbd-aa46-4f33-be3b-b7be9440b445",
        "status": "scheduled",
        "createdBy": "57646ff9-1cd3-4d3c-88ba-eb09a395366c",
        "amount": 2400,
        "updatedAt": "2021-06-10T08:20:58.539Z",
        "createdAt": "2021-06-10T08:20:58.539Z",
        "challengeId": null,
        "updatedBy": null
    },
    {
        "workPeriodId": "22d49927-d9b7-4115-8b82-aea72d44ee73",
        "error": {
            "message": "id: e09cc7d8-d898-41b2-a73d-13e569b98948 \"ResourceBooking\" Billing account is not assigned to the resource booking",
            "code": 409
        }
    },
    {
        "workPeriodId": "5e8c3e52-539d-45d0-8e66-37be3709b5f4",
        "amount": 3456.22,
        "billingAccountId": 80000068,
        "id": "c094d04c-c0f1-488a-8a9a-c87e5c826fe8",
        "status": "scheduled",
        "createdBy": "57646ff9-1cd3-4d3c-88ba-eb09a395366c",
        "updatedAt": "2021-06-10T08:20:58.592Z",
        "createdAt": "2021-06-10T08:20:58.592Z",
        "challengeId": null,
        "updatedBy": null
    },
    {
        "workPeriodId": "b7132e7c-7947-458c-829f-59bcda44da91",
        "error": {
            "message": "Can't find a member rate in work period: b7132e7c-7947-458c-829f-59bcda44da91 to calculate the amount",
            "code": 400
        }
    }
]
```

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/d7e6b09c-779a-414d-b396-57f5caf4ea31

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder . WP Payment not getting created if member rate is not there
