### ISSUE TITLE
Clarification: Do we need the ability to filter taas-teams based on user id?

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#32]
Clarification: Do we need to add  the ability to filter taas-teams based on user id, or the GET taas-teams should return only the teams for the specific user token.

For this page, we will need only taas teams belonging to the specific user.
https://mfe.topcoder-dev.com/taas/myteams

**Comment by nkumar-topcoder** [comment]
Yes, that get point specific to pull aggregate data

**Comment by SathyaJayabal** [comment]
So the GET point will only return teams the user has access to?

**Comment by nkumar-topcoder** [comment]
@SathyaJayabal yes, atleast for now. You can close this
