### ISSUE TITLE
If the WP has no working days, then WP payment is getting created but not able to view

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#323]
Description:
If the WP has no working days, then WP payment is getting created with status 200  but not able to get using GET endpoint.

@maxceem @nkumar-topcoder It's ok to not create WP payment since the amount will be 0 but while using POST it's showing success status and WP payment id also getting created

Steps to Reproduce:
1. Choose WP with no working days (day is either Sunday/Saturday)
2. Create WP payment with the WP.
3. Try to get the WP payment created with GET endpoint.

RB id: 0b0bcd7f-84ba-4fa8-afae-466665b9b258
WP id: 5ed9efb0-50f6-4cc1-8931-60e448586135
WP payment id: b07bf4f7-fdcf-40d4-a7d1-4ddc6560573c

![image](https://user-images.githubusercontent.com/55895538/121330630-25e17a80-c951-11eb-9fcd-836671ca5b47.png)
![image](https://user-images.githubusercontent.com/55895538/121331307-b750ec80-c951-11eb-9547-1dec0a67456d.png)
![image](https://user-images.githubusercontent.com/55895538/121331377-c768cc00-c951-11eb-9952-e84180b9851d.png)

**Comment by maxceem** [comment]
This is basically the same issue as here https://github.com/topcoder-platform/taas-apis/issues/307, just for one payment.

**Comment by sandhiyakavi** [comment]
Closing this issue. It will be tracked in #307

**Comment by maxceem** [comment]
After fixing another issue #307 it appeared that current issue has another root and different from #307, so we are investigating.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/d7e6b09c-779a-414d-b396-57f5caf4ea31

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/122721140-455e9880-d2ab-11eb-9335-7fc9379a5ec5.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder . If 'no-days' then WP payment not getting created
