### ISSUE TITLE
Add new value in rateType enum

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/taas-apis#331]
Add `annual` value to list
https://github.com/topcoder-platform/taas-apis/blob/925d7bd8f9933bad9b6a8e3c59b01dbd9246f1ad/src/bootstrap.js#L13

Related Change https://github.com/topcoder-platform/taas-es-processor/issues/75

Update Swagger 
https://github.com/topcoder-platform/taas-apis/blob/e76d67f5e32765ccecfd7e02b64d4d0a64cdc55f/docs/swagger.yaml#L1476

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-06-17 at 11 45 17 AM" src="https://user-images.githubusercontent.com/58783823/122341941-a90e5c00-cf61-11eb-985b-f3fcbc1b4963.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/122503863-23a7ac00-d034-11eb-9388-c06f137324f8.png)
