### ISSUE TITLE
[$30] Ability to filter by multiple `workPeriods.paymentStatus`

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#332]
We should be able to filter Work Periods by multiple `paymentStatus` in the endpoints:
- `GET /work-periods?paymentStatus=status1,status2,status3`
- `GET /resourceBookings?workPeriods.paymentStatus=status1,status2,status3`

it should support comma-separated list, or single status (which is supported now)

Update Swagger to indicate this.

**Comment by maxceem** [comment]
@sandhiyakavi this is ready for QA on DEV.

**Comment by sandhiyakavi** [comment]
@maxceem GET /resourceBookings?workPeriods.paymentStatus=status1,status2,status3 will work only with field param right?

1. GET /work-periods?paymentStatus=status1,status2,status3 - Able to get WP according to the paymentStatus provided
![image](https://user-images.githubusercontent.com/55895538/121844118-6c065780-cd1e-11eb-92a9-1771affe7689.png)

2. `{{URL}}/resourceBookings?sortBy=workPeriods.paymentStatus&sortOrder=asc&fields=workPeriods.id,status,workPeriods.userHandle,workPeriods.paymentStatus,workPeriods.projectId,workPeriods.startDate,workPeriods.endDate,workPeriods.daysWorked,id,projectId,status,startDate,endDate,memberRate&workPeriods.startDate=2021-06-06&page=1&perPage=50&status=placed&workPeriods.paymentStatus=pending,cancelled`

![image](https://user-images.githubusercontent.com/55895538/121844287-b5ef3d80-cd1e-11eb-8941-722f60087064.png)

**Comment by maxceem** [comment]
@sandhiyakavi 

> will work only with field param right?

right, we have to pass `fields` to be able to filter by `workPeriods.paymentStatus`

I'm not sure if the case 2 worked good for or is there any issue?

**Comment by sandhiyakavi** [comment]
@maxceem Yes Search ResourceBookings with field param (case 2) worked good

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/31504b6d-597c-4a3d-9799-7468f4249dd7

**Comment by maxceem** [comment]
Closing as this was only issue on DEV, and it would be implicitly tested during Admin App testing.
