### ISSUE TITLE
Add allow empty for string fields in Job and JC endpoints

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/taas-apis#334]

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/taas-apis/commit/e2fc2dd3f1fae9b27a377694c78565c24225722e

**Comment by SathyaJayabal** [comment]
@sushilshinde , still does not allow empty string
<img width="1440" alt="Screenshot 2021-06-17 at 11 50 36 AM" src="https://user-images.githubusercontent.com/58783823/122342513-58e3c980-cf62-11eb-92d9-64b86abff7b0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
