### ISSUE TITLE
Clarification: Topcoder member is able to create jobs for projects they do not have access to

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#35]
User: tester1234/ appirio123

This user does not access to any taas-teams and the GET taas-teams returns empty for this user.
But the user is able to create jobs within any project. 

Is this expected behaviour? 
I see this has been added through https://github.com/topcoder-platform/taas-apis/issues/23, but should the member be able to add jobs only to projects they are a part of ? 

@nkumar-topcoder

**Comment by SathyaJayabal** [comment]
They are also able to create a job candidate. Only when trying to create a resource booking for the project using the job, do they get `unauthorized` error.

**Comment by nkumar-topcoder** [comment]
@SathyaJayabal yes, this is as per design
