### ISSUE TITLE
[$10] Create payment by query endpoint should return query as it was sent

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#354]
When we create payments by query using `POST /work-period-payments/query` endpoint we should get `query` in response the same which we sent in request.

At the moment if we send query like this:
```js
{
  "query": {
    "status": "placed",
    "workPeriods.startDate": "2021-06-13",
    "workPeriods.paymentStatus": "completed,pending,partially-completed"
  }
}
```

We get it in response like this:
```js
{
  "total": 64,
  "query": {
    "status": "placed",
    "workPeriods.startDate": "2021-06-13T00:00:00.000Z",
    "workPeriods.paymentStatus": "completed,pending,partially-completed"
  },
  "totalSuccess": 30,
  "totalError": 34
}

```

The issue is that date format is not the same:
- in Request: "workPeriods.startDate": "2021-06-13",
- in Response: "workPeriods.startDate": "2021-06-13T00:00:00.000Z",

Date format in response should be the same like in request for all the dates.

**Comment by eisbilir** [comment]
@maxceem for the given example; `"workPeriods.paymentStatus"` returns in array format.
Therefore, I'll return `"workPeriods.paymentStatus"` as received (string or array)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/40ff0635-6d0d-445e-819f-156d62a11dff

**Comment by sandhiyakavi** [comment]
Verified on Dev env.

![image](https://user-images.githubusercontent.com/55895538/123077827-5ea34880-d455-11eb-9b8e-c325af5dea7c.png)
![image](https://user-images.githubusercontent.com/55895538/123077963-7aa6ea00-d455-11eb-87c2-7f9ea1d21c39.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod with @nkumar-topcoder
