### ISSUE TITLE
[$160] We should be able to get payments inside Work Periods inside Resource Bookings

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#355]
We have endpoint `GET /resourceBookings` which can return us WorkPeriods if we explicitly list them inside `fileds` like `workPeriods` or specific fields like `workPeriods.id`.

At the moment this endpoint doesn't allow us to get `payments` inside WorkPeriods.

There are 3 levels of this tasks.

### Return payments [$20]

- This endpoints should also return `payments` inside Work Periods if we specfiy `fields=workPeriods` (all the fields including `pyaments`) or if we explicitly specify `fields=workPeriods.payments`
- Only admins, bookings managers and M2M with correct scope should be able to get this field.

### Return particular fields of payments [$40]

- Would it be hard to also support filtering fields inside `payments` like this? `fields=workPeriods.payments.status`?
- Same like above, only admins, bookings managers and M2M with correct scope should be able to get this field.

Note, that `fields` property we have in 2 endpoints where it should be updated: `GET /resourceBookings` and `GET /resourceBookings/{id}`.

### Filter by payments fields [$100]

We would like to able to filter Resource Bookings with Work Periods by the payments fields inside. In particular, we are interested to filter by the `workPeriods.payments.status` field. But other fields which are easy to support also would be nice to have.

This should be done for DB and ES requests.

How hard would it be to implement it?

- Update Swagger.

**Comment by eisbilir** [comment]
@maxceem
when filtering by payment fields, which fields would be neded other than `status`?
we have `amount`, `billingAccountId`, `challengeId`, `memberRate`, `customerRate`, `days` as options.

**Comment by maxceem** [comment]
@eisbilir `days` for sure and `memberRate`, `customerRate` if it's not much code to add, otherwise no need them.

**Comment by eisbilir** [comment]
@maxceem
consider we have 2 RBs:

1. RB:
- 1.WP: `paymentStatus:`**`completed`** 1.payment: `status: completed` 2.payment: `status:`**`cancelled`**`
- 2.WP: `paymentStatus: partially-completed` 1.payment: `status: completed` 2.payment: `status: completed`

2. RB:
- 1.WP: `paymentStatus:`**`completed`** 1.payment: `status: completed` 2.payment: `status: completed`
- 2.WP: `paymentStatus: partially-completed` 1.payment: `status: completed` 2.payment: `status:`**`cancelled`**

our filter = `workPeriods.paymentStatus: completed` & `workPeriods.payments.status: cancelled`

returned response:

choice one:
1.RB + 1.WP + 2.WPP

choice two:
1.RB + 1.WP + 2.WPP
2.RB + (1.WP + no WPP) + (2.WP + 2.WPP)

I think we should choose choice one ?

**Comment by maxceem** [comment]
@eisbilir yes, choice 1. All conditions should be met to get returned.

**Comment by maxceem** [comment]
@eisbilir Found one issue after testing on DEV:

If we filter Resource Bookings only by `startDate=2021-06-13`: `GET /resourceBookings?workPeriods.startDate=2021-06-13&fields=id,jobId,projectId,billingAccountId,startDate,endDate,memberRate,status,workPeriods.id,workPeriods.projectId,workPeriods.userHandle,workPeriods.startDate,workPeriods.endDate,workPeriods.paymentStatus,workPeriods.paymentTotal,workPeriods.daysWorked,workPeriods.daysPaid`

we get only `3` records.

But if GET Work Periods with the same start date I get `GET /work-periods?startDate=2021-06-13` I get `70` records, which means that there should be also returned 70 RB above.

Also, I can see that on DEV after merging PR https://github.com/topcoder-platform/taas-apis/pull/357 much less records are returned. I suspect that only RB with WPPs are returned using `GET /resourceBookings` endpoint now. We previously had similar issue when we implemented filtering by WP inside RB.

**Comment by eisbilir** [comment]
@maxceem you are right in your suspicion, only RB with WPPs are returned.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/67f111e8-3abc-4db8-bc3b-50abe9e2ad6c

**Comment by maxceem** [comment]
### QA Guidelines

1. `GET https://api.topcoder-dev.com/v5/resourceBookings?fields=id,workPeriods.payments` should return RB (with id) and with `workPeriods[].payments`

   - The same for a single RB endpoint:
   
   `GET https://api.topcoder-dev.com/v5/resourceBookings/ffd8abd7-1252-4e65-a1dc-ab47a5ff5e36?fields=id,workPeriods.payments`

2. `GET https://api.topcoder-dev.com/v5/resourceBookings?fields=id,workPeriods.payments.amount` should only return RB (with id) and `workPeriods[].payments.amount`

    - The same for a single RB endpoint:
   
   `GET https://api.topcoder-dev.com/v5/resourceBookings/ffd8abd7-1252-4e65-a1dc-ab47a5ff5e36?fields=id,workPeriods.payments.amount`
   
3. We should be able to filter by `workPeriods.payments.status`, `workPeriods.payments.days`.

    Example:
    
    - `GET https://api.topcoder-dev.com/v5/resourceBookings/?fields=id,workPeriods.payments&workPeriods.payments.status=failed`
    
    In such case only RB which has WP which has WPP with status `failed` should be returned.

**Comment by sandhiyakavi** [comment]
Verified the above scenarios on Dev Env. Working as expected

**Comment by sandhiyakavi** [comment]
Issue verified in Prod through FE
