### ISSUE TITLE
Role search by JD is not returning role in some scenarios

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#360]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'Input Job Description' box
Enter any valid skill with word test in frond of the skill or after the skill(ex- test github or github test) >> search
Enter unit testing(this original skill is unit-testing) >> search
Enter 'react' 'node' >> search

**Current behavior**
All above searches do not return matching roles

https://user-images.githubusercontent.com/4592712/122520055-cc540c80-d030-11eb-8658-03942f062f55.mp4

**Comment by sexta13** [comment]
now this popup is shown:
![image](https://user-images.githubusercontent.com/5584415/123447953-53295c00-d5d2-11eb-96a4-e3708c3f5693.png)

**Comment by sdgun** [comment]
@nikolay83 This issue is not fixed, the issue we have here is that job description parser logic is detecting look-alikes/mistypes and when we enter 'test' keyword in the JD it identifies it as 'Rest'. So let's say the JD has github and the Test keyword, then it identifies github and Rest as the skills mentioned in JD, but since we don't have these 2 skills in any of our roles, there is no matching role.

Also when 'unit testing' is enetered in JD, the JD parser brings skills unit-testing and junit. Since there are no roles with these 2 skills, it brings no matching results.


https://user-images.githubusercontent.com/4592712/123582574-ac280880-d7fb-11eb-96d6-d495face18d4.mp4

**Comment by nikolay83** [comment]
@sdgun 
I guess we can close it, as there will always be some edge cases. The parsing algorithm we've implemented a quite simplistic and does not aim to have 100% accuracy. 
There is also a chance we will be using EMSI 3rd party soon.
cc: @urwithat
