### ISSUE TITLE
sendRoleSearchRequest returns role doesn't exist for some roles

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#370]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click Select on the SELECT A ROLE box
Select Role 'support Engineer' and search
Check the sendRoleSearchRequest API response

**Current behavior**
Shows a blank page

sendRoleSearchRequest API response returns message: "id: 8c76a436-3e39-4c09-8c88-6983ebd5bcc1 \"Role\" doesn't exists."

Console error observed:
![image](https://user-images.githubusercontent.com/4592712/122727290-84cdba80-d294-11eb-93b0-56b9b537509b.png)

https://user-images.githubusercontent.com/4592712/122727760-03c2f300-d295-11eb-9205-7955b0d8c63a.mp4

**Comment by eisbilir** [comment]
@nikolay83 
Role table in the UI gets the roles from ES and when we search roles via `taas-teams/sendRoleSearchRequest` it uses DB
Right now, Support Engineer role is only exists in ES. So it causes that blank page after role search request is sent.

![Postman 2021-06-24 00 39 23](https://user-images.githubusercontent.com/72204071/123176681-9679b280-d48c-11eb-8186-005fb0e0e7af.png)
![Postman 2021-06-24 00 40 10](https://user-images.githubusercontent.com/72204071/123176682-97124900-d48c-11eb-8a96-3a4f7a4d32e7.png)

Reindexing is needed to fix this issue.

**Comment by urwithat** [comment]
The mentioned role exists in ES and not in DB.
I’ve synched the roles now on the dev environment, why did the data get out of sync on ES vs DB!
Note: While investigating I found 9 active roles in DB vs 6 in ES, was this due to Bus Api being down? Needs to be investigated.
