### ISSUE TITLE
previousRoleSearchRequestId is not sent in the next sendRoleSearchRequest request

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#373]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'INPUT SKILLS' box
Select a skill that doesn't match any skill
Search(see the roleSearchRequestId in the sendRoleSearchRequest  response or in application cache)
Click Modify search criteria button
Click select button in the 'SELECT A ROLE' box
Select a role and click search
Check the sendRoleSearchRequest  request

**Current behavior**
previousRoleSearchRequestId is not sent in the next sendRoleSearchRequest request

**Expected behavior**
Reference: https://www.topcoder.com/challenges/fdc89f53-1e89-4012-93dd-1d32bd5390c5 

> previousRoleSearchRequestId: UUID // in case user hasn’t found a role and wants to modify the search criteria. We want to track all their requests though

![image](https://user-images.githubusercontent.com/4592712/122863431-59a0a500-d340-11eb-8570-6ded6e601aa4.png)

**Comment by sexta13** [comment]
![image](https://user-images.githubusercontent.com/5584415/123447139-6be54200-d5d1-11eb-8027-5f6da07c3b84.png)

This is one is fixed already

**Comment by sdgun** [comment]
Verified in Dev, previousRoleSearchRequestId is sent in the next sendRoleSearchRequest request.

![image](https://user-images.githubusercontent.com/4592712/123583655-9fa4af80-d7fd-11eb-8af4-faaf594c86a9.png)
