### ISSUE TITLE
All the rates are not displayed to the internal users

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#381]
**Steps**
Go to https://platform.topcoder-dev.com/taas/myteams/createnewteam
Click select button in the 'select a role' box
Select a role >> search
Check the rates tab

**Current behavior**
Even though the API response returns all rates, the rate tab doesn't show them.
Also the external user is true in the Search API response, but this user is an internal user who is in wipro-all group

**Comment by eisbilir** [comment]
@sdgun Could you please share the handle of the user you tested with?

**Comment by sdgun** [comment]
Verified with Tonyj and dan_developer user in Dev, this issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/123205103-eb421b00-d4d6-11eb-829e-ac74d3326273.png)

**Comment by sdgun** [comment]
Verified in production, this issue is fixed.

![Internal](https://user-images.githubusercontent.com/4592712/123240720-2c99f100-d4fe-11eb-99a0-4e7f4538dd44.png)
