### ISSUE TITLE
Internal server error from sendRoleSearchRequest API for some JDs

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#402]
**Steps**
Enter below JD in the JD 
Click search
Click continue

Description:
[JD.txt](https://github.com/topcoder-platform/taas-apis/files/6829164/JD.txt)

Throws an internal error

![image](https://user-images.githubusercontent.com/4592712/125919057-1d0d2073-03a6-4493-be8e-6bfa24878479.png)

**Comment by yoution** [comment]
@sdgun @nikolay83 , sorry, I can not reproduce it
![image](https://user-images.githubusercontent.com/3863914/126184819-53b31dc1-6b3b-4f10-ba99-4969a1fdea35.png)

**Comment by sdgun** [comment]
@yoution Please note, this happens when you click that continue button.

**Comment by yoution** [comment]
@sdgun because the description text are too long, so BE shows error

**Comment by nikolay83** [comment]
@yoution A validation error message be displayed in this case and won't allow the user to proceed?
Could you please add it?

**Comment by nikolay83** [comment]
@sdgun @yoution 
but is the description longer than 100K char? Why?

**Comment by yoution** [comment]
@nikolay83 I find the issue
https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L795
https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L983
I will fix it

**Comment by sdgun** [comment]
> @sdgun @yoution
> but is the description longer than 100K char? Why?

@nikolay83 It's only 1999 chars

**Comment by sdgun** [comment]
Verified in dev, not fixed

**Comment by yoution** [comment]
@nikolay83 @sdgun please check my video
I found this issue happend, bacase the skills api is not stable,
https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L776
https://monosnap.com/file/lU9rH40uJ15XbHJqDPILJwWgyaPUeH

**Comment by nikolay83** [comment]
@yoution 
By "skills api is not stable" do you mean it's a bug in TeamService code and is it an issue with an instance it is run at?

**Comment by yoution** [comment]
@nikolay83 `https://api.topcoder-dev.com/v5/skills` this api is not stable

**Comment by nikolay83** [comment]
@urwithat @maxceem could you please advise?

**Comment by maxceem** [comment]
@nikolay83 from the video https://monosnap.com/file/lU9rH40uJ15XbHJqDPILJwWgyaPUeH it's not clear what causes this issue, so it's hard to say.

**Comment by urwithat** [comment]
@yoution - the issue i see in `taas-api` logs is related to character length:
`TeamService roleSearchRequest ERROR : value too long for type character varying(2000)`

Can you share your postman curl, i could try to replicate.

@nikolay83 - We need to handle validation of character length in the api., should not return back `Internal server error`

**Comment by urwithat** [comment]
Here is the curl that returns `internal servcer error`:

curl --location --request POST 'https://api.topcoder-dev.com/v5/taas-teams/sendRoleSearchRequest' \
--header 'Authorization: Bearer tokenHere' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jobDescription": "Data Science Data Visualization Big data Database Nulla maximus placerat turpis ut cursus. Pellentesque aliquet varius tellus sed feugiat. Sed ac nisi ac nisi fentum convallis eget a tellus. Donec sollicitudin in quam eu aliquet. Morbi suscipit a nulla at lobortis. Duis congue id eros a ornare. Nulla eu est in metus tempor pretium vel sed lacus. Donec cursus blandit euismod. Praesent non faucibus lacus. Praesent a nisl id purus tempor accumsan. Duis aliquam augue sed sem iaculis, ac tempor lacus dignissim. Fusce dapibus faucibus finibus. Nullam a fringilla mauris. Fusce eu faucibus nunc. Duis suscipit posuere metus, lacinia suscipit ex venenatis sit amet. Fusce quis lectus ut tellus fringilla tincidunt id eu lectus. Vestibulum ullamcorper vestibulum tristique. Ut pretium feugiat molestie. Sed vel mauris tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras dictum sapien e, vitae interdum nisi tempor eget. Nullam et tincidunt odio, quis iaculis. Aliquam sit amet justo ex. Donec rutrum lobortis arcu vel faucibus. Phasellus id lorem vitae torto olestie condimentum ac quis enim. Sed sed luctus orci. Nam varius pharetra enim, ut accumsan justo mattis iaculis. Suspendisse potenti. Donec justo mauris, aliquam eu tempus tempor, efficitur non orci. Phasellus blandit nunc vel arcu tristique bibendum. Nam eu sapien consequat, euismod in, cursus sem. Nullam vel efficitur ex, a consectetur magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque odio ligula, dignissim tincidunt egestas vel, aliquam eget ex. Vestibulum ullamcorper augue justo, ut consequat erat convallis eu. Vestibulum blandit dolor tellus, sit amet egestas nulla eleifend quis. Vestibulum e ipsum pris in faucibus orci luctus et ultrices posuere cubilia curae. Vestibulum e ipsum pris in faucibus orci luctus Suspendisse potenti. Donec justo mauris, aliquam eu tempus tempor, efficitur non orci. Phasellus blandit nunc velaa"
}'

**The jobDescription is `299 words 2,001 characters` long, if you remove one characters it works.**

**Comment by yoution** [comment]
@urwithat  In terms of phenomenon，if you remove some characters it works, but BE has no characters length restriction.
I can not reproduce the issue locally again, https://monosnap.com/file/l219bh8isJ7JrpLCshCebTZayfuhlW
I think the skill api issue about stability has been fixed.
if you input more characters, will match more skills, and then search skills in the `role` model
https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L766
maybe  the role model is not created successfully?

**Comment by eisbilir** [comment]
@urwithat Can I make a comment if you don't mind. It's clearly related to character length. I suspect following migration script has not run yet:
https://github.com/topcoder-platform/taas-apis/blob/dev/migrations/2021-07-15-role-search-request-make-job-description-length-100K.js

**Comment by urwithat** [comment]
@eisbilir, @nikolay83 - Thank you for identifying missing migration script execution on dev, have executed the migration script now.
@sdgun can you please verify on dev

**Comment by sdgun** [comment]
Verified in Dev with the max chars 100k, this issue is fixed.

[JD.txt](https://github.com/topcoder-platform/taas-apis/files/6866912/JD.1.txt)

**Comment by sdgun** [comment]
Verified in production, this issue is fixed.
