### ISSUE TITLE
Add new filter to the GET Resource Bookings endpoint

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#409]
We would like to be able to filter by `Alerts` column in the TaaS Admin App, see issue https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/72:

![image](https://user-images.githubusercontent.com/146016/126164090-a82660e1-2c26-442c-b6a9-1df2722fed8c.png)

To be able to do so, we have to update endpoint `GET /resourceBookings` to filter data by 3 criteria:
1. return RB which don't have Billing Account assigned, i. e. where `ResourceBookings.billingAccountId === null`. How to do this?

We already can filter ResourceBookings by the `workPeriods.startDate` which would only return ResourceBookings which have this week. Now we would like to 2 additional filters:
2. `workPeriods.isFirstWeek` - should only return RB if the week which matches `workPeriods.startDate`  is the first one in the RB
3. `workPeriods.isLastWeek` - should only return RB if the week which matches `workPeriods.startDate`  is the last one in the RB
Can we make such requests without updating the DB/ES model for WorkPeriods and without keeping such a flag in WorkPeriods?

### General Requirements

Update swagger.

**Comment by eisbilir** [comment]
#411
topcoder-platform/taas-es-processor#85

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/2e158479-6e38-4fd8-b731-336cb677cceb

**Comment by sandhiyakavi** [comment]
Verified in Dev Env  through FE https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/72

**Comment by sandhiyakavi** [comment]
Verified on Prod through FE https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/72
