### ISSUE TITLE
Add "customerRate" and "memberRate" fields to the "Job" model

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#41]
As per design, we have to show the rate for open positions (jobs)

![image](https://user-images.githubusercontent.com/146016/101145342-52bf7880-3622-11eb-9ef4-cdc248a1d68c.png)

But we don't have any place to store it in the Jobs model. So we have to add
- "customerRate" field 
- "memberRate" field (I guess we could also need it to match jobs with member rates later)

@nkumar-topcoder what do you think about this? As I'm not sure about business requirements here.

There is not yet clarification form @wdprice on this https://github.com/topcoder-platform/taas-app/issues/9.

**Comment by nkumar-topcoder** [comment]
@maxceem those 2 rates are available at resourceBooking model.

**Comment by nkumar-topcoder** [comment]
@maxceem we need to discuss on this, the rate has to come from RateMaster table and should be associated with Job model (JobID, JobDescription). This gives us flexibility to change cust. and member rate at TaaS admin app (future roadmap).

**Comment by maxceem** [comment]
@nkumar-topcoder do you have any details to share on where the Job **rate** would come from, so we can show it in UI:

![](https://user-images.githubusercontent.com/146016/101145342-52bf7880-3622-11eb-9ef4-cdc248a1d68c.png)

**Comment by maxceem** [comment]
As was clarified by Will on call, we shouldn't show it for the first release, so removed in it in UI:

![image](https://user-images.githubusercontent.com/146016/102346211-29e69e00-3fa7-11eb-819d-aedf5c405aa7.png)
