### ISSUE TITLE
Challenge deadlines displayed as Invalid date for the payment challenges created

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#426]
Description:

Payment challenge created has 'Invalid date' displayed under the challenge deadlines.

sample: https://www.topcoder-dev.com/challenges/327eb39d-0a8a-4563-a24b-d97a024f06be
https://www.topcoder-dev.com/challenges/85cf9523-331f-4e95-b246-2a09c6e47a95

![image](https://user-images.githubusercontent.com/55895538/126766423-ea75ccf3-9be6-4efb-96a5-32fb55d7039d.png)

**Comment by sandhiyakavi** [comment]
It is displaying correctly now.

<img width="959" alt="invalid_error_gone" src="https://user-images.githubusercontent.com/55895538/128505905-bd9ae39a-4aaa-4370-8f52-55cb20a6245a.png">

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @sandhiyakavi -  this was fixed by https://github.com/topcoder-platform/community-app/issues/5655 right?
