### ISSUE TITLE
Send in-app (web) notifications

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#477]
- **Post Interview Candidate Action Reminder**
  - TO: team members
  - Content: `Candidate action required for <strong>{userHandle}</strong> in job <strong>{Job Title}</strong> of the team <strong>{Team Name}</strong>`
  - LinkTo: `https://platform.topcoder-dev.com/taas/myteams/{projectId}/positions/{jobId}/candidates/interviews`, example https://platform.topcoder-dev.com/taas/myteams/17993/positions/d24ac836-94bd-4f09-bea6-c3bf7b6dbd1c/candidates/interviews
  - Data: `userHandle`, `jobTitle`, `teamName`, `projectId`, `jobId`
  - Type: `taas.notification.post-interview-action-required`
  - Bundle: no  
  - Example Kafka Message:
     ```js
      {
        "topic": "notifications.action.create",
        "originator": "max-manual",
        "timestamp": "2018-02-16T00:00:00",
        "mime-type": "application/json",
        "payload": {
          "notifications": [
            {
              "serviceId": "web",
              "type": "taas.notification.post-interview-action-required",
              "details": {
                "recipients": [{ "handle": "pshah_manager" }],
                "contents": {
                  "jobTitle": "JOB NOTIFICATION TEST 4",
                  "teamName": "NOTIFICATION TEST TEAM 4",
                  "projectId": 18244,
                  "jobId": "b0e42752-20c0-400c-95fc-2bab4db8d07c",
                  "userHandle": "topacc_three"
                },
                "version": 1
              }
            }
          ]
        }
      }
     ```

- **Upcoming Resource Booking Expiration**
  - TO: team members
  - Content: `{numOfExpiringResourceBookings} resource booking{s} {is/are} expiring in the team <strong>{Team Name}</strong>.`
  - LinkTo: `https://platform.topcoder-dev.com/taas/myteams/{projectId}`, example https://platform.topcoder-dev.com/taas/myteams/17993
  - Data:  `teamName`, `projectId`, `numOfExpiringResourceBookings`
  - Type: `taas.notification.resource-booking-expiration`  
  - Bundle: no
  - Example Kafka Message:
    ```js
    {
      "topic": "notifications.action.create",
      "originator": "max-manual",
      "timestamp": "2018-02-16T00:00:00",
      "mime-type": "application/json",
      "payload": {
        "notifications": [
          {
            "serviceId": "web",
            "type": "taas.notification.resource-booking-expiration",
            "details": {
              "recipients": [{ "handle": "pshah_manager" }],
              "contents": {
                "teamName": "NOTIFICATION TEST TEAM 4",
                "projectId": 18244,
                "numOfExpiringResourceBookings": 2
              },
              "version": 1
            }
          }
        ]
      }
    }

    ```

- **Resource Booking is Placed**
  - TO: team members
  - Content: `Resource <strong>{userHandle}</strong> is placed for the job <strong>{Job Title}</strong> of the team <strong>{Team Name}</strong>.`
  - LinkTo: `https://platform.topcoder-dev.com/taas/myteams/{projectId}`, example https://platform.topcoder-dev.com/taas/myteams/17993
  - Data:  `teamName`, `projectId`, `userHandle`, `jobTitle`
  - Type: `taas.notification.resource-booking-placed`  
  - Bundle: no
  - Example Kafka Message:
     ```js
      {
        "topic": "notifications.action.create",
        "originator": "max-manual",
        "timestamp": "2018-02-16T00:00:00",
        "mime-type": "application/json",
        "payload": {
          "notifications": [
            {
              "serviceId": "web",
              "type": "taas.notification.resource-booking-placed",
              "details": {
                "recipients": [{ "handle": "pshah_manager" }],
                "contents": {
                  "jobTitle": "JOB NOTIFICATION TEST 4",
                  "teamName": "NOTIFICATION TEST TEAM 4",
                  "projectId": 18244,
                  "userHandle": "pshah_manager"
                },
                "version": 1
              }
            }
          ]
        }
      }
     ```

**Comment by maxceem** [comment]
Inside TaaS App https://platform.topcoder-dev.com/taas/myteams and TaaS Admin App https://platform.topcoder-dev.com/taas-admin/work-periods?startDate=2021-08-08&by=user_handle&order=asc&perPage=10&page=1 we have to show TaaS related notifications instead of "community" related notifications which are currently shown.

To do so, we have to implement a few things:
1. Each of the apps TaaS App https://github.com/topcoder-platform/taas-app and TaaS Admin App https://github.com/topcoder-platform/micro-frontends-taas-admin-app has to set notification platform to `taas` using a method `setNotificationPlatform` provided by the navbar https://github.com/topcoder-platform/micro-frontends-navbar-app/blob/dev/src/topcoder-micro-frontends-navbar-app.js#L47. 
   - for the reference see how to call a method from navbar https://github.com/topcoder-platform/micro-frontends-taas-admin-app/blob/feature/payment-updates/src/root.component.jsx#L19
   
2. The next step would be to config rendering of the notifications similar way how it's done for other notifications, see file https://github.com/topcoder-platform/micro-frontends-navbar-app/blob/dev/src/constants/notifications.js
    - We have to render notifications text as per `Content` field in issue description above
    - Data is already provided via API
       
        ![image](https://user-images.githubusercontent.com/146016/129059676-a37bf7db-c045-4cc4-a806-955788f38301.png)
     - When we click notification it should bring us to the page as per `LinkTo`. Note, that this link should be rendered differently for DEV and PROD environment as per configured BASE URL `https://platform.topcoder-dev.com/` vs `https://platform.topcoder.com/`

**Comment by maxceem** [comment]
### Send In-App notifications from TaaS API Notifications Scheduler

We already send email notifications for
- Post Interview Candidate Action Reminder
- Upcoming Resource Booking Expiration

Additionally to email we also have to show notifications inside application, like this https://monosnap.com/file/LxairgU4K6NPdGN4Id9h7MZ2ceksQ8. For the UI side it's already implemented. The only things we have to do is send these notifications using TaaS API together with email notifications.

To send in-app notifications we should use the same Kafka Message which we use for sending emails, and we just have to include info inside Kafka Message Payload like this https://gist.github.com/maxceem/bb2ad68d2f8a790f01e3326f9f8015eb#file-notification-action-create-js-L72-L92.

We already send in-app notification here https://github.com/topcoder-platform/taas-apis/blob/feature/notifications-api/src/eventHandlers/ResourceBookingEventHandler.js#L116-L126.

And now we have to update code to send "Post Interview Candidate Action Reminder" and " Upcoming Resource Booking Expiration" notifications to be send not only by email by also by "web" (in-app).

To do so we would have to update `EmailNotificationService`:
- rename `EmailNotificationService` to `NotificationsSchedulerService` because it would send not only emails, but also "web" and possibly "slack" notification by scheduler
- similar to https://github.com/topcoder-platform/taas-apis/blob/feature/notifications-api/src/eventHandlers/ResourceBookingEventHandler.js#L116-L126 send "web" notification together with email notifications. Fields to send inside `contents' is listed inside the task above https://github.com/topcoder-platform/taas-apis/issues/477#issue-966723484

**Comment by maxceem** [comment]
First part https://github.com/topcoder-platform/taas-apis/issues/477#issuecomment-896934900 has been paid via https://www.topcoder.com/challenges/a18d33cf-d820-4e76-8fb5-6b4600082a30 for @nqviet.

@tejad payment for the second part as per comment https://github.com/topcoder-platform/taas-apis/issues/477#issuecomment-898886697 has been paid via https://www.topcoder.com/challenges/79139c7c-0f6a-479c-bef1-44cd17003fde

**Comment by sdgun** [comment]
Verified in Dev, reported issues:

https://github.com/topcoder-platform/taas-apis/issues/516
https://github.com/topcoder-platform/taas-apis/issues/515
https://github.com/topcoder-platform/taas-apis/issues/512

**Comment by sdgun** [comment]
All above issues are fixed in Dev.
