### ISSUE TITLE
Upgrade to new Skills API  from Ubahn Skills and enrich disintegration

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#486]
Upgrade to new Skills API  from Ubahn Skills and enrich disintegration

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/taas-apis/pull/478

**Comment by SathyaJayabal** [comment]
@vikasrohit ,
1. Skills associated with a job are displayed on the Team details page. but the same are not displyed on the job detail or the edit job page.
example:
https://platform.topcoder-dev.com/taas/myteams/18176
https://platform.topcoder-dev.com/taas/myteams/18176/positions/019a328e-d328-4e6f-8724-3f211ec24ced/edit
https://platform.topcoder-dev.com/taas/myteams/18176/positions/019a328e-d328-4e6f-8724-3f211ec24ced
<img width="1440" alt="Screenshot 2021-08-16 at 6 01 18 PM" src="https://user-images.githubusercontent.com/58783823/129564277-2ec2f24d-ed26-4eb8-bdc6-5d7d57b17419.png">
<img width="1440" alt="Screenshot 2021-08-16 at 6 01 42 PM" src="https://user-images.githubusercontent.com/58783823/129564300-b7cc259c-b2b1-4787-872e-08b85c6701ec.png">
<img width="1440" alt="Screenshot 2021-08-16 at 6 01 54 PM" src="https://user-images.githubusercontent.com/58783823/129564306-9dd467ae-36cd-4ac2-beab-67682d98e89c.png">

**Comment by SathyaJayabal** [comment]
@vikasrohit ,
2. While creating a team with selcting a role, we have the skills associated with the role displayed correctly, but we get an error while creating a team
Example:
https://platform.topcoder-dev.com/taas/createnewteam/role -> select .NET Engineer
<img width="1440" alt="Screenshot 2021-08-16 at 6 11 29 PM" src="https://user-images.githubusercontent.com/58783823/129565425-0e793d71-8c6a-471e-8f6f-12b6e1f70e91.png">

Continue with the flow and try to create a role, we get the  following errors. 
<img width="1440" alt="Screenshot 2021-08-16 at 6 16 30 PM" src="https://user-images.githubusercontent.com/58783823/129565986-bd35757c-51e7-492a-b532-d4aee54772b5.png">

<img width="1440" alt="Screenshot 2021-08-16 at 6 09 08 PM" src="https://user-images.githubusercontent.com/58783823/129566282-f7d676b1-e467-49fa-a2d6-dcb1309be7b3.png">

**Comment by SathyaJayabal** [comment]
3. We get an error while trying to create a team with job description
<img width="1440" alt="Screenshot 2021-08-16 at 6 21 20 PM" src="https://user-images.githubusercontent.com/58783823/129566670-fb23ceb4-e8b0-40a2-baf1-be62c1023256.png">

**Comment by SathyaJayabal** [comment]
4. There are some discrepancies with the skills data. for example, please compare the skills returned for serach term java.
<img width="1440" alt="Screenshot 2021-08-16 at 6 28 35 PM" src="https://user-images.githubusercontent.com/58783823/129567482-84975f0b-8fea-49b2-beff-91e6882798fb.png">
<img width="1440" alt="Screenshot 2021-08-16 at 6 28 22 PM" src="https://user-images.githubusercontent.com/58783823/129567550-c61cf6a5-851f-4139-a21b-c051b735c096.png">

Also we get an error while updating an existing role
<img width="1440" alt="Screenshot 2021-08-16 at 6 30 26 PM" src="https://user-images.githubusercontent.com/58783823/129567764-43a84735-1695-42fa-8116-6202ff827818.png">

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. 

Test results: https://docs.google.com/spreadsheets/d/1vFG9Nltqp2chMi6OWZZtXSDIguH-tBp6/edit#gid=1753008439

All the above issues are fixed.

**Comment by vikasrohit** [comment]
Awesome!! Thanks for validating all the cases @sandhiyakavi @SathyaJayabal

**Comment by sandhiyakavi** [comment]
Verified on PRod Env. Working as expected.
![image](https://user-images.githubusercontent.com/55895538/130060963-f55e4b05-b1dc-4c6c-b1ab-4230f291a926.png)
![image](https://user-images.githubusercontent.com/55895538/130061025-0a563f16-e70f-48fc-b032-4f6be08b464e.png)
![image](https://user-images.githubusercontent.com/55895538/130061102-45a687a3-02b0-4800-82ef-521d7ee3252d.png)
![image](https://user-images.githubusercontent.com/55895538/130061157-56de1ce0-98b3-4657-bf4f-eeb35e94686c.png)


cc: @vikasrohit @SathyaJayabal
