### ISSUE TITLE
Weekly cost not calculating in taas-teams API

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-apis#49]
See response from taas-teams API:

![image](https://user-images.githubusercontent.com/6014049/101539473-942a8d80-396c-11eb-96f6-025989984d09.png)

Expected value is 13.

**Comment by nkumar-topcoder** [comment]
@wdprice 
Verified the full output for this projects, For all Jobs the dates are past and for the last one ("id": "49d7d7x-......)  has  correct dates but status is "sourcing". Only "assigned" status has weeklycost displayed.Update status it should reflect.

**Comment by maxceem** [comment]
I've added demo data, so now we can see that cost is calculated correctly:

![image](https://user-images.githubusercontent.com/146016/102348492-a929a100-3faa-11eb-8cc2-c7c1603587e3.png)
