### ISSUE TITLE
Interview coming up email content/title are different in the emails sent to attendees(interviewers) and names missing in the title for member

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#502]
**Steps**
Have two interviewers in the interview
check the two emails sent to them 1 hour before the interview time

Email content is different, also the title is missing the candidate name in one email(looks like the same email sent to the member is coming to the second interviewer)

Team: https://platform.topcoder-dev.com/taas/myteams/18361
Interview: https://platform.topcoder-dev.com/taas/myteams/18361/positions/17a74bde-a156-4c66-8fcf-557e2c8e19e1/candidates/interviews

Primary interviewer:
![image](https://user-images.githubusercontent.com/4592712/129848289-7fea924a-ec59-412e-8750-8715579af1b6.png)

Other interviewer:
![image](https://user-images.githubusercontent.com/4592712/129848369-b1e74ebc-4435-42af-bb3d-dff2b291c8b1.png)

Member:
![image](https://user-images.githubusercontent.com/4592712/129849288-c74270e5-3ca4-4a8b-9a77-76f2c8ab5bc7.png)

**Comment by maxceem** [comment]
@wdprice @urwithat could you please help to clarify the logic here.

The current logic is like this:
- The person who creates invitation is the host and only this person get email with the full list of attendees like this:

    ![image](https://user-images.githubusercontent.com/146016/129945784-742cd74c-1799-4292-8ae8-bacfd88cb773.png)

- All other people who were listed in the invitation and the Job candidate are treated as guests and they get simple invitation with only Host Name listed in the title and general info and interview like this:

    ![image](https://user-images.githubusercontent.com/146016/129945942-53eafc84-ba6f-4230-9551-9b85976ec607.png)


Is this expected, or should be there some other logic and content of these emails?

**Comment by urwithat** [comment]
This is expected behaviour
