### ISSUE TITLE
Interview completed email is not sent at the expected time and it seems like Post Interview Action Reminder from the email body

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#504]
**Steps**
Interview: https://platform.topcoder-dev.com/taas/myteams/18361/positions/17a74bde-a156-4c66-8fcf-557e2c8e19e1/candidates/interviews

Below are the emails received by the host, see the time it is received(just 1.5hrs after interview reminder, which means 30 mins after the interview. In the requirement the expectation is 4 hours after interview time):

![image](https://user-images.githubusercontent.com/4592712/129852043-ea8e2869-255d-4f51-a637-346a5cf271ec.png)

The second email content:
![image](https://user-images.githubusercontent.com/4592712/129852197-e1726752-5719-47ed-85bb-80b29e0b5441.png)

**Comment by sdgun** [comment]
@maxceem I am not seeing the interview completed email being sent at all in dev now. If this is working in prod may be we can close this out.

Interview: https://platform.topcoder-dev.com/taas/myteams/18591/positions/df2b16ff-4934-43b4-b934-40343b760767/candidates/interviews

Primary interviewer's email: 
![image](https://user-images.githubusercontent.com/4592712/130556390-b46b537c-0684-4897-86d7-a05cddde6046.png)

**Comment by maxceem** [comment]
@sdgun I've made some improvements and it should work good now. Could you please give it a try again.

Also, please check interview coming up emails too, as they also might be affected by the fix.

**Comment by sdgun** [comment]
I had 2 interviews set up and received the emails on interview completion as expected after 4 hours of interview time, also received the interview coming up emails.

![image](https://user-images.githubusercontent.com/4592712/131959878-960631e2-a84e-4735-acad-4b1aba943c4f.png)
