### ISSUE TITLE
Candidates available for review email is not sent to the members with project access

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#505]
**Steps**
Team: https://platform.topcoder-dev.com/taas/myteams/18361/positions/17a74bde-a156-4c66-8fcf-557e2c8e19e1/candidates/to-review
One candidate is scheduled for an interview and the other one is in pending but no email has received to any of the members in the project

Email of project member taasintake11 :
![image](https://user-images.githubusercontent.com/4592712/129853913-8c887267-1a3b-4313-a766-15b5ad9905c0.png)

Email of project member sdgun:
![image](https://user-images.githubusercontent.com/4592712/129854069-71434502-a579-4399-a1c3-d332d06a346b.png)

**Comment by maxceem** [comment]
This email is sent daily, let's try to wait for 24 hours if the emails would come.

**Comment by maxceem** [comment]
@sdgun it should be fixed now. You might receive a few emails every 30 minutes during testing this issue on DEV.

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/130386865-3b85d705-c3e3-42bb-a2b8-5fbb92200071.png)

**Comment by sdgun** [comment]
Closing the issue -unable to verify in production,
