### ISSUE TITLE
When creating a TAAS project from connect app, new job created email is sent

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#510]
**Steps**
Create a TAAS project from connect by adding some positions
Check the email of the project created user

 New job created emails are sent for each position, but it shouldn't be sent

Ex-https://connect.topcoder-dev.com/projects/18387

**Comment by maxceem** [comment]
@urwithat just would like to confirm that we have to fix this: emails should not come about jobs created during project creation in Connect App?

**Comment by urwithat** [comment]
This is expected behaviour
