### ISSUE TITLE
Not able to get interview by the updated xaiId from Db.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#522]
Description:

Not able to get interview by the updated xaiId from Db but able to get through ES.

Steps to Reproduce:

1. Change the status of Jobcandidate to interview and requestinterview.
2. Patch the xaiId of the interview.
3. GET interview by xaiId.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/130929229-6b83f52b-e434-4a14-a21e-fb67af0e715b.png)
![image](https://user-images.githubusercontent.com/55895538/130929432-78577cb1-0877-417e-9126-939bb30b2655.png)
![image](https://user-images.githubusercontent.com/55895538/130929509-ac64706d-b57f-4112-bf44-8dcda30b8025.png)

Job: https://platform.topcoder-dev.com/taas/myteams/18644/positions/cb37a71b-f9a0-4565-a1e2-82eea79e0b25
Job candidate Id: 1f71a3dc-db45-4024-82b9-20346b7e7184

**Comment by yoution** [comment]
@sandhiyakavi I found the reason, because `xaiId` and normal `id` are all uuid format, so search in db will treat `xaiId` as `id`,  but this issue is not caused by me, does it need to be fixed?
https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/InterviewService.js#L174,L190

**Comment by yoution** [comment]
@sandhiyakavi   or maybe the code is right, and `xaiId` you input in the postman is wrong? it should not be `uuid` format?

**Comment by sandhiyakavi** [comment]
Closing the issue as it is working fine with the correct uuid format, Seems the one mentioned in the postman sample  is old format.

![image](https://user-images.githubusercontent.com/55895538/131444671-f8629f06-e0d1-4a92-8028-06b0a42665c6.png)
