### ISSUE TITLE
Interview status from x.ai is not synced back to Taas

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#525]
Interview status form x.ai is not synced back to Taas
Example:
job id: d88cbada-5ca5-46e9-aba7-331302f8cd76
candidate id:
1011a326-0ad0-4442-ad1f-5754c4c6a269
interview id:
98b7bd86-ed44-4ebb-b07b-eaa1fee225bc

Interview has been scheduled, but status is still as scheduling on Taas
<img width="566" alt="Screenshot 2021-08-27 at 11 24 07 AM" src="https://user-images.githubusercontent.com/58783823/131079019-4f64392e-76b4-45ec-8456-e8d52b3db721.png">
<img width="1110" alt="Screenshot 2021-08-27 at 11 25 46 AM" src="https://user-images.githubusercontent.com/58783823/131079048-ce243c74-0f00-4052-9de3-171a8830d35f.png">

**Comment by yoution** [comment]
@SathyaJayabal  can you tell me how to sync form x.ai  to Taas, I can not find the code related to it

**Comment by SathyaJayabal** [comment]
@nikolay83 , can you help with this please?

**Comment by yoution** [comment]
@sandhiyakavi I can not login to the `xai` system, can you check the api, when you change the status?

**Comment by SathyaJayabal** [comment]
@yoution , pls check here. 
https://github.com/topcoder-platform/taas-apis/blob/bf00b256428844dd3b5dee82094af56d37a31e78/src/services/InterviewService.js

example:
https://github.com/topcoder-platform/taas-apis/blob/bf00b256428844dd3b5dee82094af56d37a31e78/src/services/InterviewService.js#L340

**Comment by SathyaJayabal** [comment]
@yoution , do you have a test user(on dev) for whom you have the access to their email. Please give me the user's ahndle and email address. I can set up the interview for that user. You will have to check the email from x.ai and then select a time slot for the interview. This will should update the interview status to"scheduled".

**Comment by yoution** [comment]
@SathyaJayabal i don't have

**Comment by yoution** [comment]
@SathyaJayabal I register a dev user, yoution, and zhuyan207@gmail.com, please try

**Comment by SathyaJayabal** [comment]
@yoution , I  have messaged you on slack.

**Comment by yoution** [comment]
@sachin-maheshwari  I call the `udpateInterview` api locally, it can update correctly, 
so currently I don't know how `x.ai` update the `taas` project, which api does `x.api` invoke?

**Comment by SathyaJayabal** [comment]
@yoution @sachin-maheshwari, the issue seems to be resolved now. I am able to see the details of the scheduled interview on Taas app.
<img width="1434" alt="Screenshot 2021-08-31 at 12 29 32 PM" src="https://user-images.githubusercontent.com/58783823/131457401-39b3c768-1682-4f9c-bf88-b651369587c6.png">

**Comment by SathyaJayabal** [comment]
I ma closing this and will reopen if we face the issue again.
