### ISSUE TITLE
Split email template and update text

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#528]
### Background

We have 12 kind of email notifications, which are at the moment presented using 1 HTML template https://github.com/topcoder-platform/taas-apis/blob/dev/data/notifications-email-template.html.
This email template is inserted into sendgird and we render different email depend on the data we pass there.

Such a big single template is hard to edit from Sendgrid by managers, also, some data we pass from API so managers cannot edit it from Sengrid. 
- We would like to split this template into separate email template for each notification. 
- And we should stop passing data from API which can be edited directly in template.

### Task

1. Split HTML template https://github.com/topcoder-platform/taas-apis/blob/dev/data/notifications-email-template.html into separate HTML template for each kind of email.
    - We should be able to defined Sendgrid Template Id for each of these templates by ENV var.
    - `{{description}}` should **not** be passed from API anymore, it should be included directly inside the template as text, so managers could edit it there. If there is any other hardcoded text which we pass from API we should not pass it anymore and should include directly in email template.

2. Update each email text as per document https://docs.google.com/document/d/1L3_1SWwjwfpbiddLWwxDBD1HebRK2iT_pmBPehz2yKo/edit
    - insert tables which we have now instead of `<TABLE>`
    - make space between text and table
    - see how to match text from document to email https://monosnap.com/file/WGsx6tVdTVBBtAXM4VimRomdNpz5ji

3. Update script https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/demo-email-notifications so it can render demo notifications using different templates for demo.

4. For verification, please, provide screenshot and rendered HTML file for each kind of 12 email notifications.

**Comment by xxcxy** [comment]
there are only 10 email notifications in the doc. @maxceem

**Comment by maxceem** [comment]
@xxcxy the other 2 keep as it is, no need to change the text for them.

**Comment by xxcxy** [comment]
done. https://github.com/topcoder-platform/taas-apis/pull/529
@maxceem

**Comment by maxceem** [comment]
Thanks @xxcxy, sorry, I was not clear enough. The other 2 - don't update text.
But we need to split them into separate templates too.

So we should have 12 separate email templates in total.

**Comment by maxceem** [comment]
one more thing @xxcxy regarding mapping of the text to email template. The text which goes before table should be small like text below table. Next to the icon we place only "Speech bubble" text.

![image](https://user-images.githubusercontent.com/146016/131622966-3781ad97-01a2-4e40-93cd-eee81e98c233.png)

So it should look like this:

![image](https://user-images.githubusercontent.com/146016/131623418-9eabacb7-b8db-43a3-ba6d-bdc852dd461a.png)

**Comment by maxceem** [comment]
just in case, there should be space after grey area and before table:

![image](https://user-images.githubusercontent.com/146016/131623690-3258fac8-c53c-4429-a14c-f6d20821db8c.png)

**Comment by xxcxy** [comment]
done.
file address: https://drive.google.com/file/d/1zpfy7BDxcwFEY0W0t2UUJRh21vNi_Xfm/view?usp=sharing

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/03f225e6-7b60-4bb4-af0c-409621a7bc8f
