### ISSUE TITLE
[UI] Jobcandidates status updates

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/taas-apis#53]
enhancement:

1. At TaaS app update jobCandidate status based on the question.
  Interested in this candidate?
Yes means “Shortlisted”, no means “rejected” status.

![image](https://user-images.githubusercontent.com/33625707/102071004-e6185b00-3e25-11eb-8129-8004ec30e747.png)

2.  Hide schedule interview button.

![image](https://user-images.githubusercontent.com/33625707/102071286-427b7a80-3e26-11eb-8b2e-1857f15ecab7.png)

**Comment by maxceem** [comment]
Created corresponding issue in the TaaS App repository to handle it there https://github.com/topcoder-platform/taas-app/issues/25

**Comment by maxceem** [comment]
Done in TaaS App repo, see for details https://github.com/topcoder-platform/taas-app/issues/25
