### ISSUE TITLE
Issues with Post Interview Action Reminder email notification when interview 2 is scheduled

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#540]
**Steps**
**Issue 1** 
In the below instance, noticed two records on the same candidate interview 1 and 2. When we schedule interview 2 we shouldn't receive post interview reminder on interview 1)

![image](https://user-images.githubusercontent.com/4592712/132159902-c5bdd046-22a1-4d8c-87df-e9174d304b69.png)

Job title: ABC
Link to the interview: https://platform.topcoder-dev.com/taas/myteams/18690/positions/05bdcac3-b86b-4070-bfe3-483c1cb47706/candidates/interviews

**Issue 2**
No Post Interview Action Reminder email notification received on the below Interview 2 but received in app notification:

Interview(2):
https://platform.topcoder-dev.com/taas/myteams/18690/positions/05bdcac3-b86b-4070-bfe3-483c1cb47706/candidates/interviews

Gmail(only received interview completed email):
![image](https://user-images.githubusercontent.com/4592712/132160368-f336aa09-2529-4f74-a0ac-08ce08adfa21.png)

In app notifications are received as expected:
![image](https://user-images.githubusercontent.com/4592712/132160318-28c8d993-5c64-40dc-aa33-d801c95c6961.png)

**Comment by maxceem** [comment]
We also must ensure, that we don't send duplicate notification for interview completed reminder ('taas.notification.interview-awaits-resolution'). It should also only include the last round of the interview and not list all the interview rounds per Job Candidate.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/c9133133-ce3f-4aa5-a762-7cd8c705c0fe

**Comment by maxceem** [comment]
@sdgun the first part of this issue is ready for review.

QA guidelines:
- check that if we schedule 2-3 rounds then Post Interview Action Reminder email list only the latest round for the Job Candidate
- verify the same for Interview Awaits Resolution email

**Comment by sdgun** [comment]
Verified Post Interview Action Reminder email and  Interview Awaits Resolution email with 1st, 2nd and 3rd interviews, both emails only had the latest round for the job candidate.
