### ISSUE TITLE
Interview completed email notification should not be sent if action was taken on the Job Candidate

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#541]
We have email of type `'taas.notification.interview-awaits-resolution'` which is sent 4 hours after interview start time to remind manager to take an action on the candidate after the interview https://github.com/topcoder-platform/taas-apis/blob/revert-532-feature/revert-splitting-email-templates/src/services/NotificationsSchedulerService.js#L276-L334

Though if manager already took action, such reminder should **not** be sent, while now it would be sent.

Technically this means, that we have to additionally check that corresponding JobCandiate status is `interview`.

- Demo script https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/demo-email-notifications should work good after this fix.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/1d17ae3f-26b8-4416-88e1-82b956339ab3

**Comment by maxceem** [comment]
@sdgun this is ready for QA.

QA Guideline:
- verify that Interview Awaits Resolution email notifications doesn't come if we approve or decline corresponding Job Candidate
- for regression, verify that if we don't approve/decline corresponding Job Candidate, then Interview Awaits Resolution would come

**Comment by sdgun** [comment]
Verified Interview Awaits Resolution email by selecting/declining candidates - Emails were not received
Verified Interview Awaits Resolution email by not taking any actions - Emails were received
