### ISSUE TITLE
Filtering Jobs by jobLocation doesn't work 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#556]
**Steps**
Call Get https://api.topcoder-dev.com/v5/jobs?jobLocation=India

It brings jobs with all locations, not only the jobLocation=India

![image](https://user-images.githubusercontent.com/4592712/134626647-26441173-d1e8-492d-910d-36259587414e.png)

**Comment by LieutenantRoger** [comment]
@sdgun @SathyaJayabal This issue is resolved and has been deployed, it's using wildcard to do the filter of the job based on jobLocation

**Comment by sdgun** [comment]
@LieutenantRoger Do we only support one location at a time? like Location=US and EU,India

**Comment by LieutenantRoger** [comment]
Yes, Location is a dropdown list with single select option, so we don't support multiple location. So if you fill `US and EU,India` It will try to match a location contains `US and EU,India`

**Comment by LieutenantRoger** [comment]
The behavior shall be the same with this page: https://www.topcoder.com/gigs for location dropdown for your reference.

**Comment by sdgun** [comment]
Verified in Dev, issue is fixed.
