### ISSUE TITLE
POST: Does not save the new job flag fields

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#557]
1. Use Post to create a JOB with job flag fields.
<img width="1440" alt="Screenshot 2021-09-24 at 2 31 53 PM" src="https://user-images.githubusercontent.com/58783823/134648624-7ad4dd55-3d05-4772-8a8c-7a4622872ca2.png">
Job is created and the response has the correct data for the job flag fields

2. User GET to view the job created in step 1
<img width="1440" alt="Screenshot 2021-09-24 at 2 32 11 PM" src="https://user-images.githubusercontent.com/58783823/134648756-279f9cce-2762-4cf8-ac0e-e032aafede09.png">
The job flag fields have the default values and not the values used in step 1.

**Comment by LieutenantRoger** [comment]
Suspect this is an issue with the zap syncing system. @SathyaJayabal  will work with @nkumar-topcoder @sushilshinde to work through the syncing process of the zap system next Week.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , check out this scenario please.
1. Patch details for the new flags with some values.
2. Now patch the job and update any other field, example , start date 
3. All the new fields data is now default values.

I guess for the POST case, same thing is happening
When user creates job with flag details it gets created correctly
When RCRM patches the external id of the job, these flag details are going back to default.
So the issue is with the PATCH. PATCH any other field is resetting the flag field values to default.

**Comment by LieutenantRoger** [comment]
@SathyaJayabal I think I have fixed this one and the dev env has been deployed.
