### ISSUE TITLE
[$100] Send Email Notifications when meeting scheduled

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#586]
Branch: `feature/interview-update`.

#### Background

I've noticed one thing regarding Zoom link and Nylas workflow.
When the meeting is scheduled by Nylas both Customer (host) and Job Candidate (guest) receive email with the same Zoom Link. Though to be able to connect using Zoom, host has to use special host link and guest has to use another kind of link for guests. Until host doesn't join meeting using special host link, the meeting would not begin, see screenshot attached.

![image](https://user-images.githubusercontent.com/146016/138294299-bdbecde0-a1e1-45a9-b990-a386371412d5.png)

#### Task

As Nylas sends the same link to both customer and Job Candidate. So I guess what we have to do:
- disable the notification sent by Nylas - uncomment [these lines](https://github.com/topcoder-platform/taas-apis/blob/feature/interview-update/src/services/NylasService.js#L103-L105) to disable Nylas built-in email notifications 
- send confirmation emails using TaaS API (with different Zoom links to Customer and Job Candidate)

- Learn how to send notifications from this challenge specification https://www.topcoder.com/challenges/ff6dec7b-db8b-4687-bd28-c393a59712dd?tab=details
- This email has to be send when Interview status is changed to `Scheduled` or `Rescheduled` from some other status.
- **Customer Email Data**:
   - Subject: `Candidate confirmed meeting on {Tuesday Nov. 2nd, 11:00 am}` (replace with correct datetime)
   - Body: 
      ```
      Hi {Customer Full Name},

      You're booked! You're meeting with {Job Candidate Full Name} on {Tuesday Nov. 2nd, 11:00 am}.

     Job: {Job title}
     Interviewee: {Job Candidate Full Name}
     Zoom link: {Customer Zoom Link}
     Start: {Tuesday Nov. 2nd, 11:00 am}
     End: {Tuesday Nov. 2nd, 11:30 am}
     Timezone: {Europe/Kiev}
      ```

- **Job Candidate Email Data**:
   - Subject: `You're meeting on {Tuesday Nov. 2nd, 11:00 am}` (replace with correct datetime)
   - Body: 
      ```
      Hi {Job Candidate Full Name},

      You're booked! You're meeting with {Customer Full Name} on {Tuesday Nov. 2nd, 11:00 am}.

     Job: {Job title}
     Interviewer: {Customer Full Name}
     Zoom link: {Job Candidate Zoom Link}
     Start: {Tuesday Nov. 2nd, 11:00 am}
     End: {Tuesday Nov. 2nd, 11:30 am}
     Timezone: {Europe/Kiev}
      ```
      
- We have to tigger these notifications using internal event similar to how we send interview invitation notification here https://github.com/topcoder-platform/taas-apis/blob/feature/interview-update/src/eventHandlers/InterviewEventHandler.js#L210      
      
#### Verification

Update [demo script](https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/demo-email-notifications) so it would trigger sending these notifications for demo.

Provide screenshots of both emails.

**Comment by maxceem** [comment]
@nkumar-topcoder would need your help to check Sendgrid.
- it looks like templates `taas.notification.interview-link-for-guest` and `taas.notification.interview-link-for-host` are mixed up. Could you please check that these templates in Sendrid have source code from the correct html file. And that env variable for it has corresponding id in AWS env file.
- also, we would need to set subject in Sendgrid to `{{subject}}` - this has to be done for all templates in Sendgrid.

@sdgun

**Comment by sdgun** [comment]
@maxceem Now we can see the subject in the email but in the email sent to the host, we see below issue

![image](https://user-images.githubusercontent.com/4592712/140018024-706184d8-ea58-4f03-8672-c1fe0c2dbe4f.png)

**Comment by sdgun** [comment]
@maxceem The issues mentioned in my comment [above](https://github.com/topcoder-platform/taas-apis/issues/586#issuecomment-954648138) are present in the expired email notification too

**Comment by maxceem** [comment]
@sdgun could you please share the screenshot of expired email example?

**Comment by sdgun** [comment]
@maxceem Please ignore the issue on expired notification, there was a miscommunication, we don't have the issues mentioned in my comment in expired notifications.

**Comment by maxceem** [comment]
@sdgun this has to be fixed now and ready for QA https://github.com/topcoder-platform/taas-apis/issues/586#issuecomment-958685451

**Comment by sdgun** [comment]
@maxceem Interview scheduled email is not sent now

Example Interviews:
https://platform.topcoder-dev.com/taas/myteams/18969/positions/0efdcf55-3b3f-490e-aa77-66523acb5dd8/candidates/interviews

**Comment by sdgun** [comment]
Interview scheduled email is being sent now
