### ISSUE TITLE
[$250] Cancel and Re-schedule interview meetings

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#587]
## Expected outcome

Implement functionality to cancel and re-schedule interviews by Customer and Job Candidate.

## Task

When we send emails confirming meeting to Customer and Job Candidate we have to include links which could be followed to Cancel or Re-schedule interview.

## TaaS API

To support cancel and reschedule features we have to do 2 additional things when processing create event webhook in `partiallyUpdateInterviewByWebhook`:
- save `booking.calendar_event_id` to `Interview` model new field `nylasEventId`
- save `booking.edit_hash ` to `Interview` model new field `nylasEventEditHash`
- do all necessary changes after adding these fields to the model as per [Code Guidelines](https://github.com/topcoder-platform/taas-apis#-code-guidelines)
- Migration script should remove all existent interviews as since now we would rely on these new fields, and we don't know them for existent interviews. [See how to correctly do it](https://github.com/topcoder-platform/taas-apis/blob/dev/migrations/2021-09-30-interview-nylas.js#L21-L37).

### Support Cancel Interview

We already support it, as we listen to the global nylas webhook, and cancel it. But we have to make a couple of improvements:
- Before marking Interview as cancelled check if `Interview.nylasEventId` === `event.id`. So we should only cancel interview if we've got webhook about the same event id. Otherwise we should ignore it.
- Only change status of the interview to `Cancelled` if it's not cancelled yet.

### Update Interview confirmation emails

When Job Candidate confirms interview we are sending email with meeting details like https://monosnap.com/file/UJhzY51D7oDDg7c0MPxncDjxR3mKvq.

Below meeting details add the next text to each email template:
```
To cancel or reschedule, click the links below:
Cancel | Reschedule
```

- `Cancel` link should lead to `https://platform.topcoder-dev.com/taas/interview/{interviewId}/cancel`
- `Reschedule` link should lead to `https://platform.topcoder-dev.com/taas/interview/{interviewId}/reschedule`

### Update `cancel` and `reschedule` links in Nylas event description

- Nylas event description is populated by Nylas like this: `"description":"\n\nTo make changes to this event, click the links below:\n\nReschedule: https://schedule.nylas.com/tc-taas-interview-f7e0c707-e8d4-4d51-8a10-5a8ea4c66028/reschedule/Q5J7EKu8SQRg41T1ro4c5w?email=maxceem.dev@gmail.com&name=Maksym1%20Dev&prefilled_readonly=true\nCancel: https://schedule.nylas.com/tc-taas-interview-f7e0c707-e8d4-4d51-8a10-5a8ea4c66028/cancel/Q5J7EKu8SQRg41T1ro4c5w?email=maxceem.dev@gmail.com&name=Maksym1%20Dev&prefilled_readonly=true"`, see another ticket where replaced parsing this description with `metadata` https://github.com/topcoder-platform/taas-apis/issues/619.
- Now we have to update these links with our TaaS links because this description would be visible inside Google calendar event.
- So when we set metadata fields here https://github.com/topcoder-platform/taas-apis/issues/619 we also have to update description of the event with TaaS Link to cancel and reschedule.
- We may just assign a new description text like: `\n\nTo make changes to this event, click the links below:\n\nReschedule: {rescheduleLink}\nCancel: {cancelLink}` don't have to parse existent description and replace links in text.

## TaaS App

Implement pages which would show Nylas Page to cancel and reschedule events. Both these pages would be similar to the page we already have in TaaS App to schedule interview. The only difference is that they would use another `iframe` URL.

### https://platform.topcoder-dev.com/taas/interview/{interviewId}/cancel

- If interview status is not `Scheduled` or `Rescheduled` then show error message: `This interview is has status {status} and cannot be cancelled`.
- Otherwise show `iframe` with the next URL `https://schedule.nylas.com/{interview.nylasPageSlug}/cancel/{interview.nylasEventEditHash?prefilled_readonly=true`

### https://platform.topcoder-dev.com/taas/interview/{interviewId}/reschedule

Very similar to cancel page.

- If interview status is not `Scheduled` or `Rescheduled` then show error message: `This interview is has status {status} and cannot be rescheduled`.
- Otherwise show `iframe` with the next URL `https://schedule.nylas.com/{interview.nylasPageSlug}/reschedule/{interview.nylasEventEditHash?prefilled_readonly=true`

## Verification

⚠️ It's important to make sure that suggested approach would work. Make all necessary fixes and improvements so it works. If there are any critical issues which is hard to solve, please let me know.

- Customer can cancel meeting.
- Customer can reschedule meeting.
- Job Candidate can cancel meeting.
- Job Candidate can reschedule meeting.

**Comment by mahidulalvi-bonic** [comment]
Hi @maxceem, I created these two PRs for this issue.
https://github.com/topcoder-platform/taas-apis/pull/622
https://github.com/topcoder-platform/taas-app/pull/574

**Comment by maxceem** [comment]
Thank you @mahidulalvi-bonic I'm checking it out.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/33727d1c-096f-4f74-b80c-92b9f587b99e

**Comment by sdgun** [comment]
Reported https://github.com/topcoder-platform/taas-app/issues/579
