### ISSUE TITLE
Zoom accounts has to be used using round-robin

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#589]
Branch: `feature/interview-update`

As per requirements in this challenge https://www.topcoder.com/challenges/af9a1041-7a78-484d-87d3-5aec9e87b578?tab=details we have to use another Zoom account every time when we schedule a meeting.

It's implemented, but a bit different. After we use the last account in the list we have to start from the first account again. So if we have 3 Zoom accounts then each time we schedule interview we would take the next one, and then from the beginning:
- 1st
- 2nd
- 3rd
- 1st
- 2nd
- 3rd 
- and so on...

**Comment by sdgun** [comment]
@maxceem In Dev we always see the zoom meetings from same account(Md Mahidul..) Can this be tested in Dev?

**Comment by maxceem** [comment]
@sdgun yes, this can be tested. 

For now we use account from Md Mahidul because Topcoder not yet provided official accounts. But technically it already works and can be tested.

One of the important cases to verify here, that customer can really connect with JC using their links.

**Comment by sdgun** [comment]
Verified joing meetings as customer and JC from the links sent in the emails. No issues in connecting but noticed the meeting is set to a recurring meeting even though there is only one occurance.

![image](https://user-images.githubusercontent.com/4592712/139649402-2f00e8eb-422f-496b-8305-84d123b8c354.png)

**Comment by sandhiyakavi** [comment]
@maxceem Both candidate as well as Customer are asked to join only as attendee and not as host, The customer is asked to sign in and join as attendee (not as host of the meeting) with the meeting password.

customer got below screen's on clicking the Zoom link.
![image (6)](https://user-images.githubusercontent.com/55895538/139650854-7f79ffb9-4a44-477b-9e9b-1fc412999d7b.png)


![image (5)](https://user-images.githubusercontent.com/55895538/139650838-f8845817-7c9c-4706-92fd-253ba8f92b23.png)

Job candidate got below screen.

![image](https://user-images.githubusercontent.com/55895538/139651226-c8733a99-e395-4feb-8945-9d405f63305c.png)

**Comment by maxceem** [comment]
@sandhiyakavi it works good to me, see demo video https://monosnap.com/file/KlC0AvTMxlgFGqHJvjF5gHQ4xaqy0z (I use Windows virtual machine to simulate 2 different computers)

Did you open these link on one computer or 2 different computers?

**Comment by sandhiyakavi** [comment]
@maxceem I used one computer but I didn't open both links at the same time. I opened only Customer link then closed it and opened Candidate link. Don't know why I was not able to host. Better we will check again and update here.

**Comment by sdgun** [comment]
I verified this using two devices, worked as expected.

**Comment by maxceem** [comment]
> @maxceem Is there any fix for #589 (comment)?

@sdgun we use this type of meeting because so we don't have to define exact time for zoom meeting as previously it was technically impossible. Now I think we can embed meeting time into zoom meeting, so it should be possible to remove this text.

Though I suggest logging it as a separate issue as the solution is not very easy.

**Comment by sdgun** [comment]
Created https://github.com/topcoder-platform/taas-apis/issues/612 on above issue.
