### ISSUE TITLE
[$50] Unify email template naming

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#605]
Branch: `feature/interview-update`

Recently we've added a lot of email templates and it become very hard to match environment variables like of email sendgrid templates, with notification topic and email template html file name:
For example notification regarding profile view:
- Environment variable is `NOTIFICATION_CLIENT_VIEWED_PROFILE_SENDGRID_TEMPLATE_ID`
- Topic is `taas.notification.job-candidate-resume-viewed`
- And HTML file name is `candidate-was-viewed-by-client-email-template.html`

### Task

We have to all these to use the same name:
- Always use topic name as a base. (Example: `taas.notification.job-candidate-resume-viewed`)
- Rename environment variable to the same (uppercase, replace all symbols to `_` and add suffix `_SENDGRID_TEMPLATE_ID`: 
   - So for example for topic `taas.notification.job-candidate-resume-viewed` the environment variables should become
`TAAS_NOTIFICATION_JOB_CANDIDATE_RESUME_VIEWED_SENDGRID_TEMPLATE_ID`
- Rename email template to be the same as topic with `.html` extension, for example `candidate-was-viewed-by-client-email-template.html` should become `taas.notification.job-candidate-resume-viewed.html`
- Make sure that we update them everywhere inside the source code including demo script https://github.com/topcoder-platform/taas-apis/blob/feature/interview-update/scripts/demo-email-notifications/index.js

### Hint

The easiest way to match everything is using files https://github.com/topcoder-platform/taas-apis/blob/feature/interview-update/config/email_template.config.js#L73-L200 and https://github.com/topcoder-platform/taas-apis/blob/feature/interview-update/scripts/demo-email-notifications/index.js#L20-L38

**Comment by sdgun** [comment]
@maxceem Is this something we can test from UI?

**Comment by maxceem** [comment]
@sdgun no, this is a code organisation issue, so cannot be QAed.

**Comment by maxceem** [comment]
Closing as it cannot be tested during QA.
