### ISSUE TITLE
[$100] Send Interview email rendering time in the timezone of the receiver (host/guest)

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#609]
At the moment we are sending all the Interview related emails showing time in the timezone of the host.

When we send email to the **guest**, we have to render all these times in the timezone of the **guest**. And when send emails to the **host** use timezone of the **host**.

We already know the the timezone of the `host` which we store inside `interview.timezone` field. We also have to gather timezone of the guest (Job Candidate) and also store it inside the interview.

- Add field `interview.guestTimezone` to the interview model.
- To populate the timezone of the Job Candidate we have to get it inside `partiallyUpdateInterviewByWebhook` method when we get create event webhook. This event [payload](https://gist.github.com/maxceem/8c00ca4aabd044a7cdf0d5a3c50397d7#file-nylas-page-webhook-payload-json-L77) has `recipient_tz` field which store timezone of the use who selected time.
   - NOTE: only save `interview.guestTimezone` the first time, if interview already has `interview.guestTimezone` defined, then DON'T update it. This is because Customer might [reschedule](https://github.com/topcoder-platform/taas-apis/issues/587) interview and then we would get Customer timezone timezone which we don't want.
- Rename field `interivew.timezone` into `interview.hostTimezone`. This is to make it clear whose timezone it is. Make sure to update it everywhere in the code.
- do all necessary changes after adding/updating these fields to the model as per [Code Guidelines](https://github.com/topcoder-platform/taas-apis#-code-guidelines)
- as we already have some interviews scheduled without `guestTimezone` migration script should copy value from `hostTimezone` to `guestTimezone` during migrating the existent interview records

Update all the email templates which we send to interview Guest and Host. We have to always show datetime in using corresponding timezone. And also, mention the correct timezone:
- `taas.notification.interview-awaits-resolution` - host
- `taas.notification.interview-coming-up-guest` - guest
- `taas.notification.interview-coming-up-host` - host
- ~`taas.notification.interview-expired-guest` - guest~ - (no dates shown in email)
- ~`taas.notification.interview-expired-host` - host~ - (no dates shown in email)
- `taas.notification.interview-link-for-guest` - guest
- `taas.notification.interview-link-for-host` - host
- ~`taas.notification.interview-schedule-reminder` - guest~ - (no dates shown in email)
- ~`taas.notification.post-interview-action-required` - host~ - (no dates shown in email)

Update/fix demo script so we could get all these emails for demo https://github.com/topcoder-platform/taas-apis/blob/dev/scripts/demo-email-notifications/index.js#L20-L37. Make sure that we see different timezone for guest and host.

**Comment by mahidulalvi-bonic** [comment]
@maxceem, what is the last time for this issue? Some additional time would be great.

**Comment by maxceem** [comment]
@mahidulalvi-bonic by when do you think you may complete it?

**Comment by maxceem** [comment]
Ok, that would be fine.

Just in case I've updated one requirement, instead of removing all the interviews during migration to "migration script should copy value from hostTimezone to guestTimezone during migrating the existent interview records".

also, could you please, get the latest changes from our `dev` branch to your dev branch as I've made some fix there

**Comment by mahidulalvi-bonic** [comment]
Yes, will do. Thanks.

**Comment by mahidulalvi-bonic** [comment]
> * NOTE: only save `interview.guestTimezone` the first time, if interview already has `interview.guestTimezone` defined, then DON'T update it. This is because Customer might [reschedule](https://github.com/topcoder-platform/taas-apis/issues/587) interview and then we would get Customer timezone timezone which we don't want.

Customer can access the calendar before the candidate, theoretically.. Then we would store customer's timezone to guest timezone.

**Comment by maxceem** [comment]
In practice I cannot see how it would happen. When customer schedules interview we only send link to select time to the candidate. So at this moment customer doesn't know where to select time.

**Comment by mahidulalvi-bonic** [comment]
@maxceem, some interview email templates don't show the timezone such as
`taas.notification.interviews-overlapping.html`

Here the 'Start time' is shown in EDT. Should I also update these? Note, so far I only found two templates which actually shows the timezones..

**Comment by maxceem** [comment]
@mahidulalvi-bonic 

we don't have to update `taas.notification.interviews-overlapping.html` as this is for Topcoder stuff and they always use EDT.

I've mentioned email templates in the task description https://github.com/topcoder-platform/taas-apis/issues/609#issue-1040136970

Most of them don't mention `timezone` that's fine. What we have to update is time which we show there.
Now we usually show time in EDT, but we have to show time in the timezone of the user who is receiving this email.

For example `taas.notification.interview-awaits-resolution`:
![image](https://user-images.githubusercontent.com/146016/140930105-cd3ea619-9008-4687-afe5-de3fe5bbddef.png)

If some email doesn't render time at all, that's fine, don't have to update it.

**Comment by maxceem** [comment]
@mahidulalvi-bonic just in case, please, create new PRs to branch `feature/interview-update-part-2`. Your previous PR has been already merged there.

**Comment by mahidulalvi-bonic** [comment]
@maxceem, I pushed this PR https://github.com/topcoder-platform/taas-apis/pull/628 with the fixes.

**Comment by mahidulalvi-bonic** [comment]
> Update/fix demo script so we could get all these emails for demo https://github.com/topcoder-platform/taas-apis/blob/dev/scripts/demo-email-notifications/index.js#L20-L37. Make sure that we see different timezone for guest and host.

I am not really sure how to see this, how do you trigger emails in demo?

**Comment by maxceem** [comment]
What this demo script does it creates such data in the DB so this notifications would be triggered during the next run CRON.

Foe example we want to test interview coming up notification which is sent 1 hour before the interview. For this purpose we create interview record in the DB with start time 1 hour 5 minutes from now. So I’m 5 minutes this notification would be triggered by TaaS API.


The second part of this demo script is listening to the Kafka events of these notifications and renders email into “out” folder.


So when we run this script what is expected:
- it would create demo data in DB which would create all the situations for these notifications 
- We wait around 5 minutes and see all notifications triggered by TaaS api and rendered into “out” folder where we cam check them

**Comment by mahidulalvi-bonic** [comment]
So I don't need to make any changes there, right? Or do I need to adjust the times etc?

**Comment by maxceem** [comment]
This script becomes quite outdated for these notifications. So we have to update it so it triggers them again.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/4d1023fc-586f-4468-a45c-4894b3692e94

**Comment by sdgun** [comment]
Verified in dev 

JC:

![image](https://user-images.githubusercontent.com/4592712/143405399-80153268-0319-489f-8f66-bcedde7ee25b.png)

![image](https://user-images.githubusercontent.com/4592712/143413361-daedc452-c9c7-40e1-9d46-6a175723c6bb.png)

Host:

![image](https://user-images.githubusercontent.com/4592712/143405428-033d3026-0495-4745-ac16-8417ea5341e9.png)

![image](https://user-images.githubusercontent.com/4592712/143413404-96d766d5-b417-4112-bf9b-ba4d6b002571.png)

**Comment by sdgun** [comment]
Verified in prod.
