### ISSUE TITLE
[$75] Fix updating interview method on webhooks

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#618]
At the moment when we listen to Nylas webhooks and update interview we are using method [updateInterviewStatus](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/NotificationsSchedulerService.js#L658-L667).
But the implementation of this method is incorrect. It only updates `status` in the DB but it updated all the fields in the ES.

It method says that is only updates status but so far it's used to update other fields too.

- Remove this method completely from the source code.
- Instead of this method use method `partiallyUpdateInterviewById`.
- But to use method `partiallyUpdateInterviewById` update it's Joi validation rule, so it makes all the fields optional - i. e. we can update only some fields, don't have to pass all the fields. Make sure that this method only updates passed fields.
- Update Swagger accordingly.

**Comment by mahidulalvi-bonic** [comment]
Hi @maxceem, I created this PR https://github.com/topcoder-platform/taas-apis/pull/622 for the issue. The requirements say I need to update Swagger docs, but method 'updateInterviewStatus' is an internal one, so I am not sure. Please let me know.

**Comment by mahidulalvi-bonic** [comment]
There are  recent changes in Interview Service 'partiallyUpdateInterviewStatus' method which has Joi validation rules different from the requirement in this issue. Should I change those?

**Comment by mahidulalvi-bonic** [comment]
So I am back to the Swagger update requirement, where should I update it? Its an internal method, right?

**Comment by maxceem** [comment]
@mahidulalvi-bonic sorry if I wasn't clear, we already have method [InterviewService.partiallyUpdateInterviewById](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/InterviewService.js#L510-L574) which is not internal. So what I mean was
- remove method [updateInterviewStatus](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/NotificationsSchedulerService.js#L658-L667)
- instead of it use method [InterviewService.partiallyUpdateInterviewById](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/InterviewService.js#L510-L574)
- but to be able to use method `partiallyUpdateInterviewById` we have to update it's Joi validation rules and to allow updating only some of the fields, now many are required, we have to make them optional https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/InterviewService.js#L542-L573

**Comment by mahidulalvi-bonic** [comment]
Got it, in some cases, the method will be called by machine - when executing cron jobs etc. What should be saved as the data.updatedBy in these cases?

**Comment by maxceem** [comment]
We would use special id of the M2M token. You may generate `currentUser` object to pass into this method like this https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L760

**Comment by mahidulalvi-bonic** [comment]
@maxceem, I have updated the PR https://github.com/topcoder-platform/taas-apis/pull/622. Please let me know.

**Comment by mahidulalvi-bonic** [comment]
How do you test from Nylas webhooks? Is there a way to trigger API calls from webhooks instead of simulating in Postman?

**Comment by maxceem** [comment]
No, I don't trigger webhook manually, I trigger by selecting time on the Nylas page after setting up the whole workflow. Here is how I do it:
- Run TaaS API
- Use `ngrok http 3000` to get public URL of local TaaS API
- Config this URL inside Nylas Dashboard
- Schedule interview using Postman:
   
    ![image](https://user-images.githubusercontent.com/146016/140614521-0cb3ef01-1af6-4159-a602-65b66c1738e0.png)
    
    NOTE: I don't use real token, the token which we have inside Postman environment should work for local setup. It doesn't expire and you don't have to update many times
    
- After that I take the `id` of created interview and just go to the page like `https://schedule.nylas.com/tc-taas-interview-%7BinterviewId%7D` on such page I can select time which would trigger the webhook.

**Comment by mahidulalvi-bonic** [comment]
I tested it using this flow, I think its working correctly by reading console logs & checking DB record.

**Comment by mahidulalvi-bonic** [comment]
Yesterday I tested it manually by calling the webhooks endpoint in the API. It was working although that endpoint expects data in a different format as given by Nylas servers.

**Comment by maxceem** [comment]
Great, thanks. I'll verify it tomorrow morning now.

From the code of view it looks good, so you may continue with other tasks. You may use the same branch so you make other fixes, already using updates you've already done.

**Comment by mahidulalvi-bonic** [comment]
Got it. Thanks.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/c1002bef-0427-4ece-8353-17e5e6f2e101
