### ISSUE TITLE
Some interviews are stuck in scheduling, therefore unable to cancel/reschedule them

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#637]
The below interview got stuck in scheduling state, but this has been already scheduled. Now this cannot be cancelled or rescheduled

https://platform.topcoder-dev.com/taas/myteams/18989/positions/e763be2c-71ae-4843-b45a-05b0ad083b65/candidates/interviews

![image](https://user-images.githubusercontent.com/4592712/143406057-5c1e32ef-a387-4e7d-b175-14af3cc3d16d.png)

**Comment by maxceem** [comment]
@sdgun this has to be fixed now.

**Comment by sdgun** [comment]
Verified in Dev

**Comment by sdgun** [comment]
Verified in Prod.
