### ISSUE TITLE
Download resume email was not received

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#689]
**Steps**
Log in to the TAAS app from acustomer user 
Go to candidates and click on the download resume link

When the resume is downloaded the first time, the candidateshould receive an email, but this is not sent

Ex team: https://platform.topcoder.com/taas/myteams/30744

**Comment by SathyaJayabal** [comment]
cc @lakshmiathreya

**Comment by SathyaJayabal** [comment]
This is working in prod.
<img width="641" alt="Screenshot 2022-04-08 at 10 46 37 AM" src="https://user-images.githubusercontent.com/58783823/162369583-230cb205-4a20-4827-9786-8935a71bba3e.png">
