### ISSUE TITLE
No JobCandidates are returned when filtering by `jobId`

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#89]
I have a Job:

![image](https://user-images.githubusercontent.com/146016/103526821-2188d100-4e8a-11eb-9fdc-8a70c197207d.png)

This Job has a JobCandidate:

![image](https://user-images.githubusercontent.com/146016/103526865-2fd6ed00-4e8a-11eb-8cb3-de6bd5f1ff19.png)

But when searching for JobCandidates and filtering by `jobId` not Job Candidates are returned:

![image](https://user-images.githubusercontent.com/146016/103527029-67de3000-4e8a-11eb-8c8a-6784ef90e0e6.png)

For testing I'm using user `tester1234` who is a `Topcoder User`.

**Comment by imcaizheng** [comment]
@maxceem Did you mean the jobCandidate can be found by querying `/jobCandidates` without filters while it cannot be found filtered by `jobId`?

In case the jobCandidate cannot be found even without filters, it could be possible that `taas-es-processor` doesn't properly create the jobCandidate in ES.

Trying to reproduce the issue, I cloned the latest commit of the `taas-apis` and followed the steps you mentioned. I am able to find the jobCandidate associated with a job using user `tester1234`.

**Comment by maxceem** [comment]
@imcaizheng 

> Did you mean the jobCandidate can be found by querying /jobCandidates without filters while it cannot be found filtered by jobId?

yes.

If I get all JobCandidates without filter, I get JobCandidate record for this Job:

![image](https://user-images.githubusercontent.com/146016/103530967-18e7c900-4e91-11eb-9d52-1df119ae3f86.png)

But if I filter, then I don't get it:

![image](https://user-images.githubusercontent.com/146016/103530899-f2299280-4e90-11eb-9798-e1f8e50b4386.png)

I also, don't get it using admin user if I filter:

![image](https://user-images.githubusercontent.com/146016/103531085-4e8cb200-4e91-11eb-9492-714ef831db58.png)

I get this issue, when I review the PR https://github.com/topcoder-platform/taas-apis/pull/87 - this is no `dev` branch.

**Comment by imcaizheng** [comment]
@maxceem I tried to run the app from PR #87 but still cannot reproduce the issue. Could you find any clue by looking at console log when querying `GET /jobCanidates`?
Also, please check whether the specific jobCandidate exists in both ES and DB.

**Comment by nkumar-topcoder** [comment]
@maxceem I verified, jobid that you highlighed and few other job id  doesn't exists in postgres or ES

**Comment by maxceem** [comment]
@nkumar-topcoder I've tested it locally, so that Job is only in my local ES/DB.

**Comment by maxceem** [comment]
I've retested it after clearing ES/DB from scratch, and I cannot reproduce this issue anymore, probably I had some corrupted data in ES. So I'm closing it.
